### ISSUE TITLE
skeleton, version 0.1

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#1]
I will create a skeleton of the project and will configure deployment pipeline

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy again

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by karato** [comment]
@yegor256 your task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-095a03ae`

**Comment by yegor256** [comment]
@karato I've spent 3 hours for the work above, including:
- configured deployment pipeline with Rultor
- configured CI pipeline with Travis
- implemented skeleton of web app
- created basic Java wireframing
- documented requirements

**Comment by karato** [comment]
> @karato I've spent 3 hours for the work above, including:
> - configured deployment pipeline with Rultor
> - configured CI pipeline with Travis
> - implemented skeleton of web app
> - created basic Java wireframing
> - documented requirements

@yegor256 thank you **3 hours** paid, transaction `000-444c68ce`

**Comment by karato** [comment]
@yegor256 Thanks so much! Your account was topped up for **30 mins** (transaction ID is `000-b2c2fa54`); +30 added to your rating, at the moment it is: [+6512](http://www.netbout.com/b/35008?open=rating)
