### ISSUE TITLE
User should be able to login/logout

### ISSUE THREAD

**Issue by ggajos** [Nerodesk/nerodesk#10]
We should implement flexible authorisation and session storage mechanism. So it would be possible to extend authorisation and support multiple "bindings". Let's focus on flexible design here. For version one we could use the easiest form of authentication. Username only :), no password.

We should be able to easily extend our auth mechanism and support login/logout using Facebook OAuth mechanism.

**Comment by yegor256** [comment]
@ggajos I think we should enable just Facebook OAuth for now. no need to create our own user registration mechanisms. Facebook OAuth will provide us the user ID, which is enough to identify the user. We just encrypt it and send back to the user in some custom `X-Nerodesk-User` cookie. that's it. no need to keep this ID anywhere locally. what do you think?

**Comment by yegor256** [comment]
@ggajos also, keep this in mind: http://www.teamed.io/policy.html#21

**Comment by ggajos** [comment]
Ok, thanks, created #15
