### ISSUE TITLE
account deletion is not implemented

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#100]
Our README specification promises that we allow users to delete accounts. This feature is not implemented at the moment, let's fix it. A user should be able to click "terminate account". Then, we show a confirmation page, with a text confirming that the account will be destroyed and all files removed. Then, the user should enter a verification text and click "confirm". Then, we do `user.docs().erase()` and all documents are erased in S3.

**Comment by karato** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by karato** [comment]
@pinaf this is your task

**Comment by k0r** [comment]
what if the user has paid access? refer to @roadmap 0.3
> user can fund his account via PayPal

**Comment by pinaf** [comment]
@yegor256 is the account actually deleted or just marked as deleted somehow in order to allow a future re-activation?

**Comment by k0r** [comment]
@pinaf [#5](https://github.com/teamed/nerodesk/issues/5)

**Comment by yegor256** [comment]
@pinaf just deleted, like I explained. We don't actually have any account persistence. As long as there are no files in S3, the account has nothing. So, we should terminate an account by removing all its files.

**Comment by yegor256** [comment]
@k0r we'll deal with paid access in a separate ticket, here we focus on account termination feature

**Comment by pinaf** [comment]
@k0r ok. so this is DELETION, not DISABLE

**Comment by pinaf** [comment]
@yegor256 got it.

**Comment by karato** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-3508f5a7

**Comment by pinaf** [comment]
@karato please assign someone else here

**Comment by karato** [comment]
> @karato please assign someone else here

@pinaf all right, we'll find someone else for this task

**Comment by karato** [comment]
@longtimeago do this task

**Comment by longtimeago** [comment]
@yegor256 Should we start from UI?

**Comment by yegor256** [comment]
@longtimeago we should always start from UI. we should start from something that is visible to the end user and then go deeper into the code, just like this article explains: http://www.yegor256.com/2015/02/12/top-down-design.html

**Comment by longtimeago** [comment]
@karato please, assign someone else. Really lack of time now, sorry :(

**Comment by k0r** [comment]
@yegor256 could you complete this?

**Comment by karato** [comment]
> @karato please, assign someone else. Really lack of time now, sorry :(

@longtimeago right, I'll try to find someone else for this task

**Comment by k0r** [comment]
@karato let's assign @krzyk, @darkled or @alevohin.

**Comment by k0r** [comment]
@yegor256 let's reformat this ticket to account cancellation rather than deletion -- accounts shouldn't be removed from the system.

**Comment by yegor256** [comment]
@k0r we don't have such a thing in our system as "account". We just have files stored in S3, in directories named after users URNs. If we delete all files, the user gets deleted automatically. So, there is no user identity persistence in the system.

**Comment by ghost** [comment]
@yegor256 should we implement user identity persistence? see discussion [#213](https://github.com/teamed/nerodesk/issues/213)

**Comment by k0r** [comment]
@yegor256 updated response.

**Comment by k0r** [comment]
@yegor256 feature omitted from the project.

**Comment by karato** [comment]
@k0r please don't close it.. @yegor256 could you please close it, if it is done?

**Comment by yegor256** [comment]
@karato no need to do this any more
