### ISSUE TITLE
file details are not visible in the list of files

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#101]
I don't see file sizes and other attributes for my files in the profile. This information would be useful:
- file size
- data/time of upload
- mime type of tile

**Comment by karato** [comment]
@yegor256 got it, tag `bug` is here

**Comment by karato** [comment]
@longtimeago this is your task

**Comment by karato** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-9491c6ab`

**Comment by longtimeago** [comment]
@karato please, assign someone else, really have no time for this issue :(

**Comment by karato** [comment]
> @karato please, assign someone else, really have no time for this issue :(

@longtimeago all right, we'll find someone else for this task

**Comment by karato** [comment]
@pinaf do this task

**Comment by pinaf** [comment]
@karato please assign someone else - waiting for another way to login to the system that isn't through facebook.

**Comment by karato** [comment]
> @karato please assign someone else - waiting for another way to login to the system that isn't through facebook.

@pinaf all right, we'll find someone else for this task

**Comment by karato** [comment]
@krzyk do this task

**Comment by krzyk** [comment]
PR #169

**Comment by krzyk** [comment]
@karato we're waiting for #169

**Comment by karato** [comment]
> @karato we're waiting for #169 

@krzyk sure, we'll wait for #169

**Comment by krzyk** [comment]
@yegor256 changes have been merged to master, please close this issue

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by karato** [comment]
2 puzzles were created here: `101-c6cd25f6`, `101-20ebe58a`

**Comment by karato** [comment]
@krzyk thanks, I just added **38 mins** to your account, payment `54694167`, 193 hours and 2 mins spent... the bonus for fast delivery (age=3199)... +38 to your rating, your total score is [+5570](http://www.netbout.com/b/35035?open=rating)

**Comment by karato** [comment]
@yegor256 the last puzzle `101-c6cd25f6`/#210 originated from here solved
