### ISSUE TITLE
total storage size is not visible

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#102]
I don't see total amount of bytes stored in my account. I believe, this information would be useful and should be present in the top line of every page. I think, we should implement it like this:

```
interface Docs {
  long size();
}
```

**Comment by karato** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by karato** [comment]
@ggajos this is your task

**Comment by karato** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-f2a4687d

**Comment by ggajos** [comment]
PR #107

**Comment by ggajos** [comment]
@yegor256 please close if that's all here, thanks

**Comment by yegor256** [comment]
@ggajos you implemented something that doesn't give any value to me. I still don't see the size in my web interface, as a user. See http://www.yegor256.com/2015/02/12/top-down-design.html

**Comment by ggajos** [comment]
@yegor256 ok, is it wrong that it will be implemented as part of dependent PDD? should I wait till is going to be impl. and then put note here?

**Comment by yegor256** [comment]
@ggajos it's not wrong. what's wrong is that you started to implement this feature from the bottom, not from the top. first thing you should have done here is to make sure **the user** sees the number on his/her web page. once it's done, you can create puzzle(s) and close the task. just my article explains. see the point?

**Comment by ggajos** [comment]
@yegor256 thank you, yes, it's obvious; what can we do now? Should I create another PR or we can wait for PDD to be implemented afterwards?

**Comment by yegor256** [comment]
@ggajos I would suggest to create another PR

**Comment by ggajos** [comment]
PR #136

**Comment by karato** [comment]
there is a puzzle in this code `102-3d5e0e72`, we'll resolve it later

**Comment by karato** [comment]
@ggajos 7 days already, in 48 hours I will re-assign; -30 added to your rating, current score is: [+3314](http://www.netbout.com/b/35094?open=rating)

**Comment by ggajos** [comment]
@karato PR #136 merged.

**Comment by karato** [comment]
@ggajos it takes too long, don't work any more. -60 to your rating, your total score is [+3254](http://www.netbout.com/b/35094?open=rating)

**Comment by ggajos** [comment]
@yegor256 please close if that's all here, thank you

**Comment by yegor256** [comment]
@ggajos thanks!

**Comment by karato** [comment]
@yegor256 last puzzled solved `102-3d5e0e72`/#209
