### ISSUE TITLE
file sharing doesn't work

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#103]
Our README promises that a user is able to share his/her files with other users. At the moment, this doesn't work. Let's implement this feature. Let's extend our interfaces with this:

``` java
interface Doc {
  // shares this document with another user
  // if this document is not mine - throws a runtime exception
  void shareWith(String urn);
  // show a list of people who I share this document with
  Iterable<String> friends();
  // stop sharing this document with this user, and prohibit access
  void prohibit(String urn);
  // return a list of friends who share something with me
  Iterable<String> sharers();
  // get documents shared with me by this user
  Iterable<Doc> access(String urn);
}
```

I think we should use DynamoDB for keeping that links between projects. I would suggest to use a table with this structure:

```
{owner, friend, document}
```

Here, `friend` is a hash, `owner` is a range, and `document`. With this structure, when "Jeff" shares a document "pic.jpg" and calls `shareWith("Sarah")`, we put this item to the DB:

```
{friend:Sarah, owner:Jeff, document:pic.jpg}
```

**Comment by karato** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by karato** [comment]
@longtimeago this is your task

**Comment by karato** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-10d2e5fd

**Comment by pinaf** [comment]
@karato we need to wait for #108

**Comment by karato** [comment]
> @karato we need to wait for #108 

@pinaf sure, let's wait for #108

**Comment by longtimeago** [comment]
@karato please, assign someone else, really have no time for this issue :(

**Comment by karato** [comment]
we waited for #108, it is closed already

**Comment by karato** [comment]
> @karato please, assign someone else, really have no time for this issue :(

@longtimeago someone else will help in this task, no problem at all

**Comment by karato** [comment]
@pinaf this is your task

**Comment by yegor256** [comment]
@pinaf do you mind if I take this task?

**Comment by pinaf** [comment]
@yegor256 not at all please go ahead

**Comment by yegor256** [comment]
@karato assign me please

**Comment by karato** [comment]
> @karato assign me please

@yegor256 sure, the ticket is yours, go ahead

**Comment by karato** [comment]
5 puzzles were created here: `103-8a2bada8`, `103-eee698c6`, `103-92c2e0c7`, `103-fed230e7`, `103-a06372a2`

**Comment by karato** [comment]
@yegor256 Thanks for your contribution, **30 mins** was added to your account, payment ID is `000-97adafc6`, 64 hours and 18 mins spent total

+30 added to your rating, current score is: [+8985](http://www.netbout.com/b/35008?open=rating)
