### ISSUE TITLE
XSLT Error

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#104]
Error:

> `<!DOCTYPE html>` displayed as plaintext

Replication:

> visit website with firefox

Browsers tested:

> chrome, firefox, safari

![xsl doctype bug](http://www.nerodesk.com/nd_doctype_bug.jpg)

**Comment by yegor256** [comment]
@karato this is definitely a bug

**Comment by karato** [comment]
> @karato this is definitely a bug

@yegor256 OK, I labeled it as `bug`

**Comment by karato** [comment]
@ggajos do this task

**Comment by k0r** [comment]
@karato ETA?

**Comment by ggajos** [comment]
PR #128

**Comment by ggajos** [comment]
@k0r fix merged with master; please close if that's all here

**Comment by ghost** [comment]
@ggajos thanks.

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.1`

**Comment by ghost** [comment]
@yegor256 thanks.

**Comment by karato** [comment]
@ggajos thank you, added **30 mins** to your acc, payment num is `AP-7LN18965BW858064L`, 98 hours and 10 mins spent in total to complete. +30 added to your rating, current score is: [+3252](http://www.netbout.com/b/35094?open=rating)
