### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by pinaf** [Nerodesk/nerodesk#108]
There doesn't seem to be a way to login without a Facebook account. In order to contribute, it is necessary for the dev to login to his local copy of nerodesk.

Please implement a way to login without Facebook (and thus gain access the restricted pages) or at least explain in README/How to contribute how that should be done if it is already possible.

**Comment by ghost** [comment]
@pinaf this was a decision made by @yegor256 here [#10](https://github.com/teamed/nerodesk/issues/10)

**Comment by pinaf** [comment]
@k0r I don't use Facebook at all and I'd bet there are other ppl who don't either :(

**Comment by ghost** [comment]
@pinaf inherent account mgmt is to be determined post 1.0 release.

**Comment by pinaf** [comment]
@k0r not sure what you mean by inherent account mgmt

**Comment by ghost** [comment]
@pinaf also refer to [#11](https://github.com/teamed/nerodesk/issues/11)

**Comment by pinaf** [comment]
@yegor256 should I just ask for someone else to be assigned or is there a way around this?

**Comment by ghost** [comment]
@pinaf oauth via fb is the only method currently available pre 1.0 for logging in.

**Comment by yegor256** [comment]
@pinaf why can't you create an account in Facebook? What is the problem with this? It's a one minute job and you will be able to use that account for OAuth logins to many online apps.

There is a workaround. We can add Github login to the system, it's 30 min job.

**Comment by pinaf** [comment]
@yegor256 don't trust them at all. want distance from those ppl.

**Comment by pinaf** [comment]
@yegor256 github would be fine with me - but regardless of my situation, it makes a lot of sense since you use github as your dev platform already.

**Comment by ghost** [comment]
@pinaf @yegor256 please utilize the provided login mechanism to login as this is currently a budgetary and time sensitive issue.

**Comment by pinaf** [comment]
@k0r I have requested someone else be assigned - sorry.

**Comment by ghost** [comment]
@pinaf could you fix this? [#104](https://github.com/teamed/nerodesk/issues/104) doesn't require login access.

**Comment by pinaf** [comment]
@k0r I sure could but that issue was assigned to @ggajos already.
