### ISSUE TITLE
User should be able to login via Facebook OAuth.

### ISSUE THREAD

**Issue by ggajos** [Nerodesk/nerodesk#11]
User should be able to login via Facebook OAuth but there is no notion about this in code yet.

We should use provided access codes and `PsFacebook` class is implemented in Takes 0.5

Access codes:
- `facebook acc ID:`provided via file`
- `secret code:`provided via file`

Please use suggested by Yegor way of providing those values (see https://github.com/teamed/nerodesk/issues/11#issuecomment-77805476)

**Comment by ggajos** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@ggajos thanks, I added the "bug" tag

**Comment by karato** [comment]
we will find someone to do this task, soon

**Comment by karato** [comment]
@darkled this is your task

**Comment by asaen** [comment]
@karato please assign someone else to this issue

**Comment by yegor256** [comment]
@ggajos could you please reformat this ticket so that it starts sound like a bug. I'm not sure I understand now what is broken and what do you expect someone to fix

**Comment by ghost** [comment]
@ggajos @yegor256 this seems more like a suggestion for handling the oauth tokens on our end than a bug, perhaps?

**Comment by yegor256** [comment]
@k0r that's exactly my point. @ggajos please reformat the ticket so that it sounds like a bug and becomes fixable

**Comment by karato** [comment]
> @karato please assign someone else to this issue

@darkled someone else will help in this task, no problem at all

**Comment by karato** [comment]
@pinaf this is your task

**Comment by pinaf** [comment]
@karato please assign to someone else. no facebook for me, sorry.

**Comment by karato** [comment]
@ggajos many thanks for the bug report, I added 15 mins to your acc, transaction `AP-1MM44861123518100`

**Comment by pinaf** [comment]
@karato please assign to someone else. no facebook for me, sorry.

**Comment by pinaf** [comment]
@karato please assign someone else.

**Comment by karato** [comment]
> @karato please assign someone else.

@pinaf right, I will find someone else, no problem

**Comment by karato** [comment]
@longtimeago do this task

**Comment by longtimeago** [comment]
@ggajos have you updated task description according to the Yegor's proposal?
Could you please define a use case for the new app? For me, it's not clear at all

Please, define what is the exact problem, how did you end up with this task? And then we decide how to solve the problem

**Comment by ggajos** [comment]
@longtimeago  Use case: User should be able to login via Facebook OAuth.

Implementation and design of OAuth will be covered along with #15 but we have to obtain tokens. See https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/v2.2. The only way to get those tokens (correct me If I'm wrong) is to create an facebook app. We have to create new facebook app and provide a way to get them in via code.

**Comment by longtimeago** [comment]
@yegor256 @ggajos Do we really want to create an application for that? Maybe mocks would be enough?
On my opinion, this task is a bit premature. We even don't have an UI endpoints

**Comment by ggajos** [comment]
@longtimeago in some point we have to create app for production; mock might be useful but we need to understand exactly how facebook auth is going to work (settings in web panel etc.); we might even create integration test that will use dev. app; it will be very useful for finalization and preparation of prod. app config on facebook; it's a big task so it's better to start it early, let's focus on creating facebook app and get right security codes.

@yegor256 I think that task is not strictly about programming but bit more about configuration; maybe dev app should be created under proper teamed.io facebook user, it can be used later on as good template for prod. env.?

**Comment by yegor256** [comment]
@k0r could you please help us here. you should go to https://developers.facebook.com and create a new application there (call it "nerodesk"). Then, you will have to create another one (call it "nerodesk-test"), which will be used for testing purposes. Please post us app ID and secret codes for the "nerodesk-test" only.

**Comment by ghost** [comment]
@yegor256 responded via email.

**Comment by longtimeago** [comment]
@yegor256 @ggajos do you still need my help here?
If you have a test app on facebook we don't need to invent something own, right?

**Comment by ggajos** [comment]
> Let's create interface that will provide Facebook codes and default implementation for now that will return those default (development) codes.

@longtimeago Yes, we have to access those codes in our app.

@yegor256 do you have access to this app(s)?

**Comment by longtimeago** [comment]
@ggajos could you please change the task description accordingly. It's still quite confusing

**Comment by ggajos** [comment]
@longtimeago well this task contain 3 steps and this simple default implementation is step 3, need to obtain those codes first and can update description so it will be clear.

**Comment by longtimeago** [comment]
@ggajos thanks, waiting for the input :)

**Comment by yegor256** [comment]
facebook acc ID: `1600031920212896`, secret code: `82cf820c610f74dcde82795f1537b693`

**Comment by yegor256** [comment]
I think we need to wait for this ticket completion: https://github.com/yegor256/takes/issues/9. Once it's ready, we can implement Facebook authentication in nerodesk

**Comment by pinaf** [comment]
@yegor256 isn't this github repo's visibility public? are those codes not sensitive?

**Comment by longtimeago** [comment]
@alex-palevsky let's wait for yegor256/takes#9

**Comment by yegor256** [comment]
@pinaf oops, my fault, this information is indeed public. I've changed the key.

**Comment by yegor256** [comment]
@ggajos @pinaf @longtimeago `PsFacebook` is implemented in Takes 0.5, please try

**Comment by longtimeago** [comment]
@ggajos @pinaf Sorry guys, I still don't understand what I need to do for this task to be done.

**Comment by longtimeago** [comment]
@alex-palevsky please, assign someone else

**Comment by ggajos** [comment]
@longtimeago looks like quite lot happen till we start issue, updated description to be more straightforward.

**Comment by pinaf** [comment]
@ggajos this repo is public - secret codes should be kept elsewhere wouldn't you say?

**Comment by ggajos** [comment]
Agree, think this key is invalid here; @yegor256 could you help here? Is there some kind of secure channel we can use for this?

**Comment by ghost** [comment]
@yegor256 @ggajos has this been resolved?

**Comment by yegor256** [comment]
@ggajos this is how it works. see this line in `.rultor.yml`: `yegor256/home#assets/nerodesk/settings.xml`. It's an "asset" that Rultor fetched from my own private repository on every release cycle. In that `settings.xml` file I keep all project secrets. Something like this:

```
<?xml version="1.0"?>
<settings>
  <profiles>
    <profile>
      <id>nerodesk</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <fb.app>1600031920212896</fb.app>
        <fb.secret><!-- skipped --></fb.secret>
      </properties>
    </profile>
  </profiles>
</settings>
```

During Maven compilation/packaging cycle you can assume that `${fb.app}` and `${fb.secret}` are available for you. You can just create `src/main/resources/fb.properties` and put something like this there:

```
facebook_app=${fb.app}
facebook_secret=${fb.secret}
```

Maven will replace these values with real data from `settings.xml`. Make sense?

**Comment by karato** [comment]
@longtimeago 7 days already, in 48 hours I will re-assign... -30 added to your rating, current score is: [+2845](http://www.netbout.com/b/35024?open=rating)

**Comment by longtimeago** [comment]
@karato please, assign someone else

**Comment by karato** [comment]
> @karato please, assign someone else

@longtimeago OK, I will try to assign someone else

**Comment by karato** [comment]
@caarlos0 do this task

**Comment by caarlos0** [comment]
@karato please assign to someone else

**Comment by karato** [comment]
> @karato please assign to someone else

@caarlos0 I will try to find someone else

**Comment by karato** [comment]
@krzyk this is your task

**Comment by yegor256** [comment]
@krzyk please wait for https://github.com/teamed/nerodesk/pull/77

**Comment by krzyk** [comment]
@karato we're waiting for #77

**Comment by karato** [comment]
> @karato we're waiting for #77 

@krzyk yes, waiting for #77

**Comment by yegor256** [comment]
@karato assign me to this pls

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.1`

**Comment by yegor256** [comment]
@rultor release tag is `0.1.2`

**Comment by yegor256** [comment]
@rultor release tag is `0.1.2`

**Comment by yegor256** [comment]
@ggajos I believe this problem is fixed, you can login with Facebook to beta.nerodesk.com

**Comment by karato** [comment]
> @karato assign me to this pls

@yegor256 sure, the ticket is yours, go ahead

**Comment by karato** [comment]
I think we can continue, impediment #77 is closed

**Comment by yegor256** [comment]
@ggajos see #87 for login issue

**Comment by ggajos** [comment]
@yegor256 ok, let's close this one

**Comment by yegor256** [comment]
@ggajos it's your ticket, please close it

**Comment by ggajos** [comment]
@yegor256 sorry, thought I did it.

**Comment by karato** [comment]
@yegor256 **30 mins** added to your account (payment number `000-58801d63`), many thanks for your contribution!. +30 added to your rating, current score is: [+8518](http://www.netbout.com/b/35008?open=rating)
