### ISSUE TITLE
AwsDocs tests are missing

### ISSUE THREAD

**Issue by longtimeago** [Nerodesk/nerodesk#112]
We need to cover AwsDocs.names() and AwsDocs.doc() with unit tests.

**Comment by karato** [comment]
I am aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@longtimeago many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `53836200`

**Comment by karato** [comment]
@pinaf this is your task

**Comment by pinaf** [comment]
@karato please see PR #123

**Comment by pinaf** [comment]
@longtimeago merged. please close if alright.

**Comment by longtimeago** [comment]
@pinaf yep, thanks!

**Comment by pinaf** [comment]
@karato done

**Comment by karato** [comment]
@pinaf Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-54X14516XE9061631`, the task took 118 hours and 28 mins)

+30 to your rating, your total score is [+5776](http://www.netbout.com/b/35128?open=rating)
