### ISSUE TITLE
AwsDoc tests are missing

### ISSUE THREAD

**Issue by longtimeago** [Nerodesk/nerodesk#113]
We need unit tests for all AwsDoc operations

**Comment by karato** [comment]
I will ask someone to take care of this task soon

**Comment by karato** [comment]
@longtimeago thank you for reporting this, I added 15 mins to your acc, transaction `53835425`

**Comment by karato** [comment]
@pinaf do this task

**Comment by pinaf** [comment]
@karato please see PR #125

**Comment by pinaf** [comment]
@longtimeago merged. please close if alright.

**Comment by longtimeago** [comment]
@pinaf yep, thanks!

**Comment by karato** [comment]
@pinaf thank you, added **30 mins** to your acc, payment num is `AP-87P79948F3194520L`, 68 hours and 21 mins spent in total to complete. added +30 to your rating, now it is equal to [+5298](http://www.netbout.com/b/35128?open=rating)
