### ISSUE TITLE
PayPal account funding doesn't work

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#118]
Our README says that a user should be able to fund his/her account through PayPal. This feature is not implemented now. We should implement `User.account()` method that should return `Account` interface, where we should be able to:

``` java
interface Account {
  // current balance in cents
  int balance(); 
  // all operations, in reverse chronological order
  // the most recent at the beginning of the list
  Iterable<String> transactions(); 
  // add new operation, either positive (funding) or negative (charging for services)
  void add(int amount, String text);
}
```

Let's show the balance of the user on the top line of each web page. Also, let's create a new page `account.xsl`, where all transactions should be visible. I think we should use DynamoDB to store the information about all transactions.

**Comment by karato** [comment]
@yegor256 OK, I labeled it as `bug`

**Comment by karato** [comment]
@krzyk this is your task

**Comment by karato** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-64774a96

**Comment by ghost** [comment]
@yegor256 this feature can be moved to 0.4 or 1.0 if necessary.

**Comment by yegor256** [comment]
@k0r right, moving to 0.4

**Comment by krzyk** [comment]
@karato we're waiting for #159

**Comment by karato** [comment]
> @karato we're waiting for #159 

@krzyk issue #159 is closed already

**Comment by krzyk** [comment]
PR #162

**Comment by krzyk** [comment]
@karato we're waiting for #162

**Comment by karato** [comment]
> @karato we're waiting for #162 

@krzyk yes, of course, we'll wait for #162

**Comment by karato** [comment]
impediment in issue #162 is closed, we can probably try to continue here

**Comment by karato** [comment]
these 2 puzzles were created in this ticket: `118-195ec13f`, `118-d8bdaae8`

**Comment by krzyk** [comment]
@yegor256 PR was merged to master,  please close this issue

**Comment by yegor256** [comment]
@krzyk the problem here is that you implemented something "for programmers" but nothing "for the user", see http://www.yegor256.com/2015/02/12/top-down-design.html. The classes you created (and unit tests) are way less important than the XSL/HTML page and an ability to click something and see how PayPal funding really works. so you basically did a bottom-up design, while a top-down is expected. see the problem?

**Comment by krzyk** [comment]
OK, so here's another PR #163

**Comment by krzyk** [comment]
@yegor256 please check the new changes

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.1`

**Comment by ghost** [comment]
@krzyk thanks.

**Comment by krzyk** [comment]
@yegor256 please close :)

**Comment by karato** [comment]
@krzyk done, I added **38 mins** in payment `54694225`, 69 hours and 19 mins spent to complete this

the bonus for fast delivery (age=2906)

+38 added to your rating, current score is: [+5608](http://www.netbout.com/b/35035?open=rating)
