### ISSUE TITLE
Let's introduce web framework

### ISSUE THREAD

**Issue by ggajos** [Nerodesk/nerodesk#12]
If we want to create webapp we have to serve CSS, html files; url mappings etc. We should not reinvent the wheel and use some existing framework that will take care of this for us.

**Comment by yegor256** [comment]
@ggajos keep in mind that every ticket, even if it's a feature request, must be formatted as a bug (see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html). you have to explain what is broken and how it's going to be fixed

**Comment by yegor256** [comment]
@ggajos also, see this: http://www.teamed.io/policy.html#21

**Comment by ggajos** [comment]
@yegor256 updated description, is it ok now?

**Comment by yegor256** [comment]
@ggajos yes, correct now

**Comment by ggajos** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@ggajos got it, tag `bug` is here

**Comment by karato** [comment]
@pinaf do this task

**Comment by pinaf** [comment]
@karato thanks. please assign me formally through github also.

**Comment by pinaf** [comment]
@karato we need to wait for #18

**Comment by pinaf** [comment]
@karato actually, please assign someone else. pulling my hair out because of maven complaining about duplicate resources..

> [WARNING] Found duplicate and different resources in [org.eclipse.jetty:jetty-http:9.0.2.v20130417,org.eclipse.jetty:jetty-io:9.0.2.v20130417,org.eclipse.jetty:jetty-security:9.0.2.v20130417,org.eclipse.jetty:jetty-server:9.0.2.v20130417,org.eclipse.jetty:jetty-servlet:9.0.2.v20130417,org.eclipse.jetty:jetty-util:9.0.2.v20130417,org.eclipse.jetty:jetty-webapp:9.0.2.v20130417,org.eclipse.jetty:jetty-xml:9.0.2.v20130417,org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016] :

If I start excluding some artifacts from the spark-code dependency then important classes end up missing in the build. Wasted enough time on this.

**Comment by yegor256** [comment]
@pinaf I believe Spark is not a final choice, but a suggestion. @ggajos what do you think about it?

**Comment by pinaf** [comment]
@yegor256 maven can be such a nightmare.. need to calm down now

**Comment by yegor256** [comment]
@pinaf it's not Maven, it's people who don't know how to manage dependencies. for example this Jetty is a nightmare. they have no idea how Maven works and put all classes into all possible JARs. when you're trying to compose them together - you get conflicts. they basically abuse Maven and when we're trying to use it the right way, we're having these complains.

if we absolutely must use Spark, we can try to replace Jetty inside it.

btw, maybe let's try to use my own framework, which I was planning to create anyway: https://github.com/yegor256/takes We can make it nice and use in this object. what do you guys think?

**Comment by pinaf** [comment]
@yegor256 does anything exist there besides the specs?

**Comment by yegor256** [comment]
@pinaf nothing. but it's easy to create everything that is required for a small project. I just don't like any existing Java web frameworks. in my opinion, they all are inspired by Spring, which is inspired by a Singleton pattern :) I'm not insisting, it's @ggajos call

**Comment by pinaf** [comment]
@yegor256 ok. and what kind of backend do you suggest? standard java http classes? or even java socket classes?

**Comment by yegor256** [comment]
@pinaf I would make the backend replaceable/injectable. The default one would be based on `com.sun.net.httpserver.HttpServer`, but we can also provide other implementations, based on jetty, netty, you name it. you're asking about "takes", right? :)

**Comment by ggajos** [comment]
@yegor256 @pinaf I don't like any of existing frameworks neither :), that's why in most cases I'm using very defensive approach. Implement all I can in plan maven project (no frontend) and include this to framework later on (Grails, Play! or whatever); delaying architecture decisions is always good.

@yegor256 do you think it make sense to introduce another project that will do everything related with framework/frontend and keep this one plan and simple? We can use https://github.com/yegor256/takes for front, I'm just bit worried about time constraints if we want to impl. all of this on our own but very like this idea. Do you think we have enough time for this?

@pinaf Thanks for complains! It's the best moment for change :). I was using Play! framework quite extensively lately as It's very mature but then for sure we have to create another project. Any Java framework coming to your mind?

**Comment by yegor256** [comment]
@ggajos I can create the core of Takes in about 4-5 days and then we'll work with it all together in our usual mode. I don't think we need too much at the beginning, but eventually will create all necessary classes. in that case we'll create something good for the market. and while I will work on Takes you will make all the rest here. I mean everything that is about S3 and file sharing. what do you think?

**Comment by ggajos** [comment]
@pinaf @yegor256 Creating Java web framework that it's finally done right sounds perfect. Let's go for it. So let's introduce frontend later. If no objections I will close this ticket, we'll create new one later. Thanks for very productive brainstorm.

**Comment by yegor256** [comment]
@ggajos ok, so I'll start working on Takes tomorrow. why closing this ticket? let's keep it alive until Takes is ready. and then we'll just use it here.

**Comment by ggajos** [comment]
@yegor256 ok, make sense, thank you.

**Comment by pinaf** [comment]
@yegor256 @ggajos I agree. let's go for it.

**Comment by pinaf** [comment]
@yegor256 @karato how do I say this is impeded? there is no other issue to wait for as of now.

**Comment by karato** [comment]
> @karato we need to wait for #18

@pinaf ok, let's wait for #18

**Comment by karato** [comment]
@ggajos thanks for the ticket, your account was topped for 15 mins, payment AP-7G2833101N366662U

**Comment by yegor256** [comment]
@karato just give us more time here

**Comment by karato** [comment]
> @karato just give us more time here

@yegor256 of course, thanks for letting me know, take your time

**Comment by yegor256** [comment]
@ggajos @pinaf  FYI, takes framework version 0.1 was released a few minutes ago. Rultor project is already using it, you can see how in its `com.rultor.web` package. If you have any questions/ideas, submit them directly to Takes github issue tracker

**Comment by ghost** [comment]
@yegor256 awesome!

**Comment by pinaf** [comment]
@yegor256 cool!

**Comment by pinaf** [comment]
@karato please see PR #41

**Comment by pinaf** [comment]
@ggajos merged. please close if alright.

**Comment by karato** [comment]
the code made here contains a puzzle `12-18bd4eea`, which will be resolved soon

**Comment by ggajos** [comment]
@pinaf thanks

**Comment by karato** [comment]
@pinaf I just added **30 mins** to your account, many thanks for your contribution... +30 added to your rating, current score is: [+2876](http://www.netbout.com/b/35128?open=rating)
