### ISSUE TITLE
Cannot login using local instance of app

### ISSUE THREAD

**Issue by ggajos** [Nerodesk/nerodesk#127]
When I manage to run application it turns out that I cannot login properly.
Got error `Invalid App ID: ${fb.app}`

Think it should be documented how it can be run properly or how to obtain/configure app.

**Comment by yegor256** [comment]
@ggajos how do you run it?

**Comment by ggajos** [comment]
from IDE:
`com.nerodesk.Launch --port=8080`
or from command line:
`mvn clean install`
`java -cp target\nerodesk.jar;target\deps\* com.nerodesk.Launch --port=8080`
same result:
![screen](https://cloud.githubusercontent.com/assets/988790/6819857/5128dfde-d2c8-11e4-8b0b-bedd92c3b282.png)

**Comment by ggajos** [comment]
@yegor256 looks like I cannot reproduce this any longer; not sure what changed
