### ISSUE TITLE
Let's create storage interface

### ISSUE THREAD

**Issue by ggajos** [Nerodesk/nerodesk#13]
We have no file management for now.

We have to implement some simple file management. Let's create `Storage` interface and simple impl. that will be able to put/get/delete any file. For now we can create simple implementation that will store all files in `~/.nerodesk/storage`.

**Comment by ggajos** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@ggajos OK, I labeled it as `bug`

**Comment by karato** [comment]
I will ask someone to take care of this task soon

**Comment by karato** [comment]
@longtimeago this is your task

**Comment by longtimeago** [comment]
PR https://github.com/teamed/nerodesk/pull/17 is available for review

**Comment by yegor256** [comment]
@ggajos again, please pay attention to the way you explain problems in bugs. they all should sound like bugs, not like feature requests. see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by karato** [comment]
@ggajos thanks for tis bug, I topped your account for 15 mins, transaction `AP-8TH23582DM258911G`

**Comment by ggajos** [comment]
@yegor256 I created bunch of tickets in a row, all bad I guess, will remember that thanks.

**Comment by karato** [comment]
2 puzzles were created here: `13-97594e76`, `13-f1fbb1e7`

**Comment by karato** [comment]
@longtimeago paid, thanks, added **30 mins** to your account, payment `52471064`... added +30 to your rating, now it is equal to [+2182](http://www.netbout.com/b/35024?open=rating)

**Comment by karato** [comment]
last 2 puzzles `13-97594e76`/#31, `13-f1fbb1e7`/#30 originated from here were solved
