### ISSUE TITLE
AwsDocs.java:75-77: This method should return valid...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#131]
Puzzle `48-f3a76cd8` in `src/main/java/com/nerodesk/om/aws/AwsDocs.java:75-77` has to be resolved: This method should return valid size of aws document storage. Currently is returning just dummy value. Remember to provide test case for that also.... The puzzle was created by Grzegorz Gajos on 20-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@carlosmiranda do this task

**Comment by carlosmiranda** [comment]
@karato we're waiting for #142 for the pull request review.

**Comment by karato** [comment]
> @karato we're waiting for #142 for the pull request review.

@carlosmiranda sure, let's wait for #142

**Comment by karato** [comment]
FYI, issue #142 is already closed, and we were waiting for it..

**Comment by karato** [comment]
there is a puzzle in this code `131-8c22737d`, we'll resolve it later

**Comment by karato** [comment]
Done, the task is closed

**Comment by karato** [comment]
@carlosmiranda thank you, added **30 mins** to your acc, payment num is `54257456`, 4 hours and 34 mins spent in total to complete. added +30 to your rating, now it is equal to [+4498](http://www.netbout.com/b/35023?open=rating)
