### ISSUE TITLE
Docs.java:66-69: This method is able to...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#132]
Puzzle `48-58361961` in `src/main/java/com/nerodesk/om/Docs.java:66-69` has to be resolved: This method is able to return total amount of bytes stored in account. There is already existing implementation for mocked storage (this interface is implemented by MkStorage). What is still missing here is that we should display this value somehow for user.... The puzzle was created by Grzegorz Gajos on 20-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@carlosmiranda this is your task

**Comment by carlosmiranda** [comment]
@ggajos I have a question for you, as you are the puzzle author. How is this different from the puzzle in #132?

**Comment by ggajos** [comment]
@carlosmiranda hmm, this is #132 :)?

**Comment by carlosmiranda** [comment]
@ggajos my bad, I meant #131. Or is this puzzle obsolete since we have a AWS implementation for it?

**Comment by ggajos** [comment]
@carlosmiranda Thanks for pointing this out. I pushed two PRs in #102 due to some misunderstanding of top-down approach and that is why we have two very similar issues. I think those are duplicates then.

**Comment by carlosmiranda** [comment]
@ggajos So, I believe this is obsolete now (especially considering the recent major refactoring). Then we just need to remove the puzzle here?

**Comment by karato** [comment]
The task is done, thanks all, I am closing it

**Comment by karato** [comment]
@carlosmiranda Much appreciated! **30 mins** was added to your account, payment ID `54286426`, time spent is 93 hours and 3 mins. +30 added to your rating, current score is: [+4543](http://www.netbout.com/b/35023?open=rating)
