### ISSUE TITLE
Exception when accessing application root

### ISSUE THREAD

**Issue by longtimeago** [Nerodesk/nerodesk#138]
Starting app in dev mode and trying to access root page http://localhost:8080/ produce 2 almost identical exceptions, like this, in logs

```
[INFO] com.nerodesk.TsApp$7: Exception thrown
org.takes.NotFoundException: nothing found
    at org.takes.facets.fork.TsFork.route(TsFork.java:103)
    at org.takes.facets.fallback.TsFallback.route(TsFallback.java:97)
    at org.takes.facets.auth.TsAuth$1.act(TsAuth.java:115)
    at org.takes.http.BkBasic.print(BkBasic.java:89)
    at org.takes.http.BkBasic.accept(BkBasic.java:73)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

On UI we can see upload form as expected

**Comment by yegor256** [comment]
@longtimeago I don't understand how I can reproduce this...

**Comment by longtimeago** [comment]
@yegor256 just try to run in dev mode

```
mvn clean integration-test -Phit-refresh -Dport=8080
```

and access `http://localhost:8080` from browser
You will see these exceptions in terminal

**Comment by karato** [comment]
I will find a developer for the task soon...

**Comment by karato** [comment]
@longtimeago thanks for tis bug, I topped your account for 15 mins, transaction `54251771`

**Comment by karato** [comment]
@carlosmiranda do this task

**Comment by carlosmiranda** [comment]
@karato please assign someone else, I'm currently swamped.

**Comment by karato** [comment]
> @karato please assign someone else, I'm currently swamped.

@carlosmiranda OK, I will try to assign someone else

**Comment by karato** [comment]
@krzyk this is your task

**Comment by krzyk** [comment]
@longtimeago Right now when I start the application with `mvn -o  integration-test -Phit-refresh -Dport=8080` and access `http://localhost:8080` I don't see any exceptions on the command line

**Comment by longtimeago** [comment]
@krzyk looks like it was fixed in some of `takes` releases. It's not reproducing anymore

**Comment by karato** [comment]
@krzyk Thank you, I have added **38 mins** to your account in payment/transaction "`55404351`", time consumed: 117 hours and 33 mins

age=2980, that's why a bonus here for fast delivery

+38 added to your rating, current score is: [+6061](http://www.netbout.com/b/35035?open=rating)
