### ISSUE TITLE
Let's create file REST resource

### ISSUE THREAD

**Issue by ggajos** [Nerodesk/nerodesk#14]
User should be able to upload/download and delete file. Because frontend is not yet specified we can introduce REST interface that could be reused later on. 

When #12 will be introduced and #13 available let's create `file` REST resource:
- PUT `/api/file/examplefilename.jpg` - uploads file and store it under specific name
- GET `/api/file/examplefilename.jpg` - gets specific file or return 404 if res. not available
- DELETE `/api/file/examplefilename.jpg` - deletes specific file or return 404 if res. not available

We should document this in readme file also.

**Comment by ggajos** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@ggajos thanks, I added the "bug" tag

**Comment by karato** [comment]
we will find someone to do this task, soon

**Comment by karato** [comment]
@darkled this is your task

**Comment by karato** [comment]
@ggajos thanks for tis bug, I topped your account for 15 mins, transaction `AP-4CU4099808644882C`

**Comment by asaen** [comment]
@ggajos am I correct thinking that this issue depends on #12 and #13 ?

**Comment by ggajos** [comment]
@darkled yes

**Comment by asaen** [comment]
@ggajos ok, thanks

**Comment by asaen** [comment]
@karato we're waiting for #12 and #13

**Comment by karato** [comment]
> @karato we're waiting for #12 and #13 

@darkled yes, right, let's wait for #12, #13

**Comment by karato** [comment]
impediment in issue #13 is closed, we can probably try to continue here

**Comment by karato** [comment]
I think we can continue, impediment #12 is closed

**Comment by asaen** [comment]
@karato assign someone else please

**Comment by karato** [comment]
> @karato assign someone else please

@darkled OK, I will try to assign someone else

**Comment by karato** [comment]
@longtimeago do this task

**Comment by longtimeago** [comment]
@ggajos IMHO, the task should be done after https://github.com/teamed/nerodesk/issues/14
Current implementation is really hard to test. What do you think?

**Comment by longtimeago** [comment]
@ggajos do we really want path to be `/api/file?name=examplefilename.jpg` ?
Maybe it would be better and simpler to have it as:
`/api/file/examplefilename.jpg` ?
This is the way Github manages it's content

**Comment by longtimeago** [comment]
@ggajos anyway, here is the PR https://github.com/teamed/nerodesk/pull/53

**Comment by ggajos** [comment]
@longtimeago yes, like your idea

**Comment by karato** [comment]
7 puzzles were created here: `14-462b19d5`, `14-9e19a32c`, `14-da645c40`, `14-7a1bdbb3`, `14-186752b9`, `14-78da13fc`, `14-8cd54fa2`

**Comment by longtimeago** [comment]
@ggajos Can we close the issue? PR was merged. Thanks!

**Comment by karato** [comment]
@longtimeago Thanks for your contribution, **30 mins** was added to your account, payment ID is `53344203`

+30 added to your rating, at the moment it is: [+3049](http://www.netbout.com/b/35024?open=rating)
