### ISSUE TITLE
TkAddFriend.java:45-47: There is no unit test...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#144]
Puzzle `103-fed230e7` in `src/main/java/com/nerodesk/takes/doc/TkAddFriend.java:45-47` has to be resolved: There is no unit test for this class. Let's create one. Also let's create an integration test, to check how this document sharing works.... The puzzle was created by Yegor Bugayenko on 25-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@carlosmiranda do this task

**Comment by carlosmiranda** [comment]
@karato we're waiting for #164.

**Comment by carlosmiranda** [comment]
See pull request #164.

**Comment by karato** [comment]
> @karato we're waiting for #164.

@carlosmiranda right, let's wait for #164

**Comment by karato** [comment]
#164 is closed, we were waiting for it.. maybe we can continue?

**Comment by karato** [comment]
2 puzzles were created here: `144-72732c33`, `144-2c03eb06`

**Comment by karato** [comment]
Closing, thanks all

**Comment by karato** [comment]
@carlosmiranda Much appreciated! **45 mins** was added to your account, payment ID `54692706`, time spent is 24 hours and 56 mins; age=1450, that's why a bonus here for fast delivery; +45 added to your rating, at the moment it is: [+5026](http://www.netbout.com/b/35023?open=rating)
