### ISSUE TITLE
file sharing doesn't really share anything

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#146]
It doesn't do anything useful now, let's implement the sharing feature

**Comment by karato** [comment]
@yegor256 OK, I labeled it as `bug`

**Comment by yegor256** [comment]
@rultor release tag is `0.3`

**Comment by karato** [comment]
@longtimeago this is your task

**Comment by karato** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-692994a9`

**Comment by yegor256** [comment]
fixed

**Comment by karato** [comment]
@longtimeago No messages from you above, won't pay for now. If I'm wrong, correct me.
