### ISSUE TITLE
AwsFriends.java:45-47: This class is not implemented...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#147]
Puzzle `103-eee698c6` in `src/main/java/com/nerodesk/om/aws/AwsFriends.java:45-47` has to be resolved: This class is not implemented and we can't really share documents between users. Let's implement it using DynamoDB or some more simple S3-only based mechanism.... The puzzle was created by Yegor Bugayenko on 25-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@longtimeago do this task

**Comment by karato** [comment]
The issue is closed

**Comment by karato** [comment]
@longtimeago I'm not sure who actually completed this task, since there were no messages from you above (correct me if I'm wrong)

**Comment by longtimeago** [comment]
@yegor256 why the issue was closed?

**Comment by yegor256** [comment]
@longtimeago because I removed the puzzle. I implemented this functionality already.

**Comment by longtimeago** [comment]
@yegor256 OK
