### ISSUE TITLE
TsDoc.java:54-56: Friend ejection is not implemented...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#149]
Puzzle `103-a06372a2` in `src/main/java/com/nerodesk/takes/doc/TsDoc.java:54-56` has to be resolved: Friend ejection is not implemented now. Let's create new "take" TkEjectFriend and implement ejection there. Also, let's not forget to create a unit test for it.... The puzzle was created by Yegor Bugayenko on 25-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@longtimeago do this task

**Comment by longtimeago** [comment]
@yegor256 do we still need the task? `TkEjectFriend` is already there

**Comment by yegor256** [comment]
@longtimeago indeed, I removed the puzzle at 8ddfb6c. thanks

**Comment by longtimeago** [comment]
@yegor256 shouldn't it be closed?

**Comment by yegor256** [comment]
@longtimeago it will be, soon

**Comment by karato** [comment]
closed since "invalid"
