### ISSUE TITLE
Let's create support for Facebook OAuth

### ISSUE THREAD

**Issue by ggajos** [Nerodesk/nerodesk#15]
User should be able to login/logout using Facebook OAuth. We have to implement it.

Facebook OAuth will provide us the user ID, which is enough to identify the user. We just encrypt it and send back to the user in some custom X-Nerodesk-User cookie.

**Comment by yegor256** [comment]
@ggajos again, format it as a bug, not a task

**Comment by ggajos** [comment]
@yegor256 thanks

**Comment by ggajos** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@ggajos OK, I labeled it as `bug`

**Comment by karato** [comment]
@pinaf do this task

**Comment by karato** [comment]
@ggajos many thanks for the bug report, I added 15 mins to your acc, transaction `AP-5JE2066950467880C`

**Comment by pinaf** [comment]
@karato please assign to someone. I don't have a facebook account to test this out.

**Comment by yegor256** [comment]
@karato give this to somebody else pls

**Comment by ggajos** [comment]
@pinaf you're not the only one I think we should create one for dev. purposes (see #11)

**Comment by karato** [comment]
> @karato give this to somebody else pls

@yegor256 got it, someone else will be assigned soon

**Comment by karato** [comment]
@darkled do this task

**Comment by asaen** [comment]
@karato assign someone else please

**Comment by karato** [comment]
> @karato assign someone else please

@darkled no problem, I will try to find somebody else

**Comment by karato** [comment]
@alevohin do this task

**Comment by alevohin** [comment]
@karato Let's wait for #11, I need it for testing.

**Comment by karato** [comment]
> @karato Let's wait for #11, I need it for testing.

@alevohin ok, let's wait for #11

**Comment by yegor256** [comment]
@alevohin please wait for https://github.com/teamed/nerodesk/pull/77

**Comment by yegor256** [comment]
@ggajos this seems to be a duplicate of #11

**Comment by ggajos** [comment]
@yegor256 yes, think I edited description and title of those tickets to be more clear and end up with duplicate; closing.

**Comment by karato** [comment]
@alevohin Much obliged! I have added **30 mins** to your account in payment "53750585"... +30 added to your rating, at the moment it is: [+1636](http://www.netbout.com/b/35105?open=rating)
