### ISSUE TITLE
Eject Link Persistence after TkEjectFriend()

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#152]
Error:

> eject link persists after friend ejected

Replication:

> add friend -- invalid or not --  to share file with then eject

Browsers tested:

> chrome, firefox, safari

![share bug](http://www.nerodesk.com/nd_share_bug.jpg)

**Comment by ghost** [comment]
@yegor256 we should probably rename the function to `TkUnshareFriend()` and `unshare` -- eject is a bit insensitive.

**Comment by yegor256** [comment]
@karato definitely a bug, thanks

**Comment by yegor256** [comment]
the problem is coming from using `split()`, that always returns an empty element, even when a string is empty

**Comment by karato** [comment]
> @karato definitely a bug, thanks

@yegor256 thanks, I added the "bug" tag

**Comment by karato** [comment]
@pinaf this is your task

**Comment by pinaf** [comment]
@karato please see PR #165

**Comment by pinaf** [comment]
@k0r fixed. please close if alright.

**Comment by ghost** [comment]
@yegor256 release tag 0.3.4.

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.4`

**Comment by ghost** [comment]
@pinaf @yegor256 thanks. if anyone wants to test this: urn:facebook:1407702746210788

**Comment by k0r** [comment]
@pinaf @yegor256 eject is fixed but logging in and logging out isn't functioning.

**Comment by karato** [comment]
@pinaf Thanks for your contribution, **38 mins** was added to your account, payment ID is `AP-8U024243L89538003`, 185 hours and 33 mins spent total. there is a bonus for fast delivery (age=2922). +38 added to your rating, at the moment it is: [+6216](http://www.netbout.com/b/35128?open=rating)
