### ISSUE TITLE
logo isn't visible on website

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#153]
Current version of README doesn't say anything about displaying the Nerodesk logo on the website. This is a bug, since this feature is important and will improve the aesthetic of the project. Let's modify the README and document this feature. Then, let's include the logo above the login/logout link and site information.

Logo can be found [here](http://www.nerodesk.com/logo.png)

Example:
![temp logo place](http://www.nerodesk.com/nd_temp_logo_place_2.jpg)

**Comment by yegor256** [comment]
@k0r I would suggest to think about the entire look-and-feel of the site, not just logo. making small changes to the layout will increase project budget significantly. I would suggest to use one ticket for the entire modification of graphic layout.

**Comment by ghost** [comment]
@yegor256 I agree, but this hasn't been defined in the technical specifications of the README.md or @roadmap. design aesthetic is a project in its own thus, I thought for the time being we could at least display the logo as these decisions are made.

**Comment by yegor256** [comment]
sure, let's put the logo there

**Comment by yegor256** [comment]
@karato it's a valid bug

**Comment by ghost** [comment]
@yegor256 thanks.

**Comment by ghost** [comment]
@yegor256 updated.

**Comment by karato** [comment]
> @karato it's a valid bug

@yegor256 right, I added the `bug` tag

**Comment by karato** [comment]
@longtimeago this is your task

**Comment by k0r** [comment]
@longtimeago reassign?

**Comment by longtimeago** [comment]
@karato please assign someone else

**Comment by ghost** [comment]
@karato let's assign @pinaf or @krzyk.

**Comment by karato** [comment]
> @karato please assign someone else

@longtimeago I will ask somebody else to pick this up

**Comment by ghost** [comment]
@yegor256 updated.

**Comment by yegor256** [comment]
@k0r looks better now, thanks

**Comment by ghost** [comment]
@yegor256 logo has been updated at the source -- should be visible on the README.md soon.

**Comment by karato** [comment]
@krzyk this is your task

**Comment by ghost** [comment]
@karato thanks.

**Comment by krzyk** [comment]
@k0r should I resize the logo or just use the one provided?

**Comment by krzyk** [comment]
@k0r I've used 50% of the original logo (it looks nicer), see PR #186

**Comment by ghost** [comment]
@krzyk thanks.

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.2`

**Comment by ghost** [comment]
@krzyk thanks.

**Comment by karato** [comment]
@krzyk I just added **38 mins** to your account, many thanks for your contribution.. 55000173 spent here; there is a bonus for fast delivery (age=2920); +38 added to your rating, at the moment it is: [+5806](http://www.netbout.com/b/35035?open=rating)
