### ISSUE TITLE
TsDoc.java:80-82: This method is way to...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#154]
Puzzle `94-7efd5d22` in `src/main/java/com/nerodesk/takes/doc/TsDoc.java:80-82` has to be resolved: This method is way to complicated and should be splitted to smaller chunks. It's very hard to test what is going on here. After splitting, it should be covered by unit tests.... The puzzle was created by Grzegorz Gajos on 27-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@pinaf this is your task

**Comment by pinaf** [comment]
@ggajos any suggestions as to how to split this? also, how should I test the new methods - by making them public?

**Comment by pinaf** [comment]
@karato please assign someone else here

**Comment by ggajos** [comment]
@pinaf there is too much independent logic involved, think we have to introduce some kind of interface so we can mock parts of logic without testing everything at once. I also don't understand why everything is handled via single route.

**Comment by karato** [comment]
> @karato please assign someone else here

@pinaf right, I'll try to find someone else for this task

**Comment by karato** [comment]
@krzyk this is your task

**Comment by krzyk** [comment]
@karato PR #196

**Comment by krzyk** [comment]
@karato we are waiting for #196

**Comment by karato** [comment]
> @karato we are waiting for #196 

@krzyk sure, let's wait for #196

**Comment by karato** [comment]
@krzyk the project is temporarily on pause, please stop working with this task, until further instructions

**Comment by karato** [comment]
@krzyk we're not on pause any more, you may continue to work with the task

**Comment by karato** [comment]
@yegor256 I'm closing the issue...

**Comment by karato** [comment]
@krzyk I added **38 mins** to your account, many thanks for working with the project! The completion time here was 55992751.

the bonus for fast delivery (age=2932)

+38 added to your rating, current score is: [+5291](http://www.netbout.com/b/35035?open=rating)
