### ISSUE TITLE
TsDoc.java:76-79: I tried to get filename...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#156]
Puzzle `94-073592b9` in `src/main/java/com/nerodesk/takes/doc/TsDoc.java:76-79` has to be resolved: I tried to get filename from file meta data and it doesn't look clean but works for now. We have to either wait for impl. from `Takes` framework or implement in this project class that is going to do this in clean way.... The puzzle was created by Grzegorz Gajos on 26-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@pinaf this is your task

**Comment by pinaf** [comment]
@karato please assign someone else.

**Comment by karato** [comment]
> @karato please assign someone else.

@pinaf right, I'll try to find someone else for this task

**Comment by karato** [comment]
@carlosmiranda do this task

**Comment by carlosmiranda** [comment]
@karato Assign someone else, I won't be able to work in the next few days.

**Comment by karato** [comment]
> @karato Assign someone else, I won't be able to work in the next few days.

@carlosmiranda I will ask somebody else to pick this up

**Comment by karato** [comment]
@caarlos0 do this task

**Comment by caarlos0** [comment]
PR is opened #181

**Comment by caarlos0** [comment]
@karato done.

**Comment by caarlos0** [comment]
@karato it's done.

**Comment by karato** [comment]
@caarlos0 I just added **38 mins** to your account, many thanks for your contribution.. AP-25M93767F0367272P spent here

age=2888, that's why a bonus here for fast delivery

+38 added to your rating, current score is: [+1471](http://www.netbout.com/b/35095?open=rating)

**Comment by ghost** [comment]
@caarlos0 thanks.

**Comment by karato** [comment]
Closing, thanks all
