### ISSUE TITLE
package-info.java:37-38: Replace all mocks provided by...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#168]
Puzzle `97-a27c5d4c` in `src/test/java/com/nerodesk/om/aws/package-info.java:37-38` has to be resolved: Replace all mocks provided by Mockito in this package by their relative Mk classes and fix all the affected tests.... The puzzle was created by Carlos A Becker on 27-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@ggajos this is your task

**Comment by ggajos** [comment]
PR #178

**Comment by ggajos** [comment]
@karato we might need more time here

**Comment by karato** [comment]
> @karato we might need more time here

@ggajos right, take your time and thanks for informing

**Comment by ggajos** [comment]
@karato #178 merged, please close if that's all here, thanks

**Comment by karato** [comment]
I am closing it, thanks all

**Comment by karato** [comment]
@ggajos thank you, added **38 mins** to your acc, payment num is `AP-8FG411965E3316647`, 172 hours and 7 mins spent in total to complete. age=2983, that's why a bonus here for fast delivery. +38 added to your rating, current score is: [+3447](http://www.netbout.com/b/35094?open=rating)
