### ISSUE TITLE
pom.xml:394-396: Line coverage is intentionally lowered...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#170]
Puzzle `97-5fc80ca1` in `pom.xml:394-396` has to be resolved: Line coverage is intentionally lowered here, in order to get version 0.2 out of the door. Let's raise it back to 75.... The puzzle was created by Carlos Alexandro Becker on 28-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@ggajos do this task

**Comment by ggajos** [comment]
@karato please assign someone else here, thanks

**Comment by karato** [comment]
> @karato please assign someone else here, thanks

@ggajos I will ask somebody else to pick this up

**Comment by karato** [comment]
@carlosmiranda this is your task

**Comment by carlosmiranda** [comment]
@karato waiting for #200 now.

**Comment by karato** [comment]
> @karato waiting for #200 now.

@carlosmiranda ok, let's wait for #200

**Comment by karato** [comment]
Issue #200 is already closed (we were waiting for it) Maybe we can continue..

**Comment by karato** [comment]
Closed, done, thanks all

**Comment by karato** [comment]
@carlosmiranda thanks, I just added **1 hour** to your account, payment `55098183`, 25 hours and 19 mins spent; age=96, that's why a bonus here for fast delivery; +60 added to your rating, at the moment it is: [+5318](http://www.netbout.com/b/35023?open=rating)
