### ISSUE TITLE
TkAddFriendTest.java:52-56: We should add an assertion...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#173]
Puzzle `144-2c03eb06` in `src/test/java/com/nerodesk/takes/doc/TkAddFriendTest.java:52-56` has to be resolved: We should add an assertion where we will check if the added friend is in fact present in doc.friends(). However, class MkFriends is not yet implemented, so it returns nothing. When it is implemented let's add that assertion to make this test more robust and comprehensive.... The puzzle was created by Carlos Miranda on 1-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@pinaf do this task

**Comment by pinaf** [comment]
@karato please see PR #183

**Comment by pinaf** [comment]
@karato merged

**Comment by karato** [comment]
once `173-3f44d78e` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by karato** [comment]
Thanks all, closed

**Comment by karato** [comment]
@pinaf done, I added **19 mins** in payment `AP-2E4299824L8162938`, 143 hours and 55 mins spent to complete this

age=2906, that's why a bonus here for fast delivery

+19 added to your rating, current score is: [+6298](http://www.netbout.com/b/35128?open=rating)
