### ISSUE TITLE
Documentation does not specify minimum Java version

### ISSUE THREAD

**Issue by pinaf** [Nerodesk/nerodesk#18]
Is Java 7 allowed or is Java 8 the minimum version? Keep in mind that Spark 2 requires Java 8.

**Comment by ggajos** [comment]
@pinaf let's use 8 for now and force that in maven config.

**Comment by ggajos** [comment]
@karato it's valid bug

**Comment by karato** [comment]
> @karato it's valid bug

@ggajos got it, tag `bug` is here

**Comment by karato** [comment]
@darkled this is your task

**Comment by karato** [comment]
@pinaf thanks for the report, I topped your acc for 15 mins, payment ID `AP-35A95113XS452774E`

**Comment by asaen** [comment]
@pinaf @ggajos it looks like we have some problems running java 8 under linux (please see #36).

**Comment by asaen** [comment]
@karato we are waiting for #36

**Comment by karato** [comment]
> @karato we are waiting for #36 

@darkled yes, waiting for #36

**Comment by asaen** [comment]
@karato we're waiting for #46

**Comment by asaen** [comment]
@pinaf it seems for the moment we are not able to use java 8 since rultor use java 7.

**Comment by pinaf** [comment]
@darkled I don't mind :) Was just complaining about lack of documentation.
@ggajos is the architect here. What do you think @ggajos ?

**Comment by karato** [comment]
> @karato we're waiting for #46 

@darkled got it, let's wait for #46

**Comment by ggajos** [comment]
@pinaf @darkled think there is no point in waiting for rultor to be compatibile. Let's downgrade minimum version to 7.

**Comment by karato** [comment]
impediment in issue #36 is closed, we can probably try to continue here

**Comment by k0r** [comment]
@ggajos do not downgrade Java versions.

**Comment by asaen** [comment]
@k0r we are not going to do it anymore, since we've found the way to use java 8 which will come with the PR #47

**Comment by ghost** [comment]
@darkled thanks.

**Comment by yegor256** [comment]
@pinaf we're using Java 7 and this is enough for us. I think this ticket can be closed. See e75bdea

**Comment by pinaf** [comment]
@yegor256 thanks

**Comment by karato** [comment]
@darkled Thank you, I have added **30 mins** to your account in payment/transaction "`53750605`"

added +30 to your rating, now it is equal to [+2050](http://www.netbout.com/b/35091?open=rating)
