### ISSUE TITLE
ThresholdInputStream.java:42-45: Create a tests for the...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#180]
Puzzle `89-fd40dace` in `src/main/java/com/nerodesk/om/ThresholdInputStream.java:42-45` has to be resolved: Create a tests for the ThresholdInputStream class. We need to make sure that it's obey the InputStream contract and throws an exception when maximum read bytes limit is reached. Also please remove this class form cobertura excludes after that.... The puzzle was created by longtimeago on 29-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@ggajos this is your task

**Comment by ggajos** [comment]
PR #204

**Comment by ghost** [comment]
@ggajos thanks.

**Comment by ggajos** [comment]
@karato merged, please close if that's all here, thanks

**Comment by karato** [comment]
the code made here contains a puzzle `180-ca462c22`/#220, which will be resolved soon

**Comment by karato** [comment]
@karato Thanks all, I am closing

**Comment by karato** [comment]
@ggajos Much appreciated! **38 mins** was added to your account, payment ID `AP-4P871594KS791351B`, time spent is 148 hours and 50 mins

there is a bonus for fast delivery (age=2927)

+38 to your rating, your total score is [+3523](http://www.netbout.com/b/35094?open=rating)
