### ISSUE TITLE
migrate to takes 0.12

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#188]
We're using version 0.11.2, which is old enough already. Let's migrate to 0.12, which removes `Takes` interface. Our code will become shorter and more solid.

**Comment by ghost** [comment]
@yegor256 thanks.

**Comment by karato** [comment]
@yegor256 do this task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-b793c2c5`

**Comment by yegor256** [comment]
PR #189

**Comment by yegor256** [comment]
done

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.3`

**Comment by karato** [comment]
@yegor256 thanks, I just added **1 hour** to your account, payment `000-2192e899`, 22 hours and 10 mins spent

age=9, that's why a bonus here for fast delivery

+60 to your rating, your total score is [+9226](http://www.netbout.com/b/35008?open=rating)
