### ISSUE TITLE
Missing JSR-303 validator

### ISSUE THREAD

**Issue by pinaf** [Nerodesk/nerodesk#19]
mvn clean install -Pqulice WARNs about  JSR-303 validator:

> [ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://aspects.jcabi.com/jsr-303.html)

**Comment by ggajos** [comment]
@karato it's valid bug

**Comment by karato** [comment]
> @karato it's valid bug

@ggajos thanks, I added the "bug" tag

**Comment by karato** [comment]
I will find a developer for the task soon...

**Comment by karato** [comment]
@ggajos do this task

**Comment by karato** [comment]
@pinaf many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-53L91722Y30834048`

**Comment by ggajos** [comment]
@pinaf already merged in #27, please close if that's all here, thank you

**Comment by pinaf** [comment]
@ggajos thank you.

**Comment by karato** [comment]
@ggajos **30 mins** sent to your balance (ID `AP-7W16365076918550U`), many thanks!

+30 to your rating, your total score is [+2340](http://www.netbout.com/b/35094?open=rating)
