### ISSUE TITLE
manifest.mf requires oauth login additions

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#193]

**Comment by k0r** [comment]
@yegor256 let's prioritize this ticket.

**Comment by yegor256** [comment]
@karato that's a bug, let's fix

**Comment by karato** [comment]
> @karato that's a bug, let's fix

@yegor256 got it, tag `bug` is here

**Comment by yegor256** [comment]
These properties are available in Maven from `settings.xml` during release: `${google.id}`, `${google.secret}`

**Comment by k0r** [comment]
@karato any updates with this task?

**Comment by k0r** [comment]
@yegor256 this ticket can be closed.

**Comment by yegor256** [comment]
@karato pls close this one

**Comment by karato** [comment]
> @karato pls close this one

@yegor256 OK, I have closed the issue as requested
