### ISSUE TITLE
current layout is not market ready

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#195]
Current layout is not ready for the market since it looks too technical and un-finished. Let's fix that with CSS tweaking.

**Comment by yegor256** [comment]
waiting for #188 to finish

**Comment by ghost** [comment]
@yegor256 thanks.

**Comment by karato** [comment]
@yegor256 do this task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-780b5c52`

**Comment by ghost** [comment]
@yegor256 I would like to be involved with this process.

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.7`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.9`

**Comment by yegor256** [comment]
@k0r take a look

**Comment by ghost** [comment]
@yegor256 you're the man, thanks.

**Comment by karato** [comment]
@yegor256 thanks, paid, **45 mins** to your account, payment ID is `000-96f5d7cb`, task took 47 hours and 48 mins to complete

there is a bonus for fast delivery (age=1543)

added +45 to your rating, now it is equal to [+9184](http://www.netbout.com/b/35008?open=rating)
