### ISSUE TITLE
hardcoded file size

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#197]
![file info bug](http://www.nerodesk.com/nd_file_info_bug.jpg)

**Comment by ghost** [comment]
@yegor256 valid?

**Comment by yegor256** [comment]
yes, but we already have a puzzle for this problem: https://github.com/teamed/nerodesk/blob/master/src/main/java/com/nerodesk/om/aws/AwsDoc.java#L52-L55 We'll convert it to a ticket soon and resolve. Thanks for reporting anyway!

**Comment by ghost** [comment]
@yegor256 let's keep this ticket open and valid until this is resolved.
