### ISSUE TITLE
Code coverage check is missing

### ISSUE THREAD

**Issue by longtimeago** [Nerodesk/nerodesk#20]
Code coverage check is missing.
I propose to configure `cobertura-maven-plugin` as a separate profile in `pom.xml` to check code coverage by tests

**Comment by ggajos** [comment]
@karato it's valid bug

**Comment by karato** [comment]
> @karato it's valid bug

@ggajos got it, tag `bug` is here

**Comment by karato** [comment]
I am aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@darkled do this task

**Comment by karato** [comment]
@longtimeago many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `52471134`

**Comment by asaen** [comment]
@karato we're waiting for #34 here

**Comment by karato** [comment]
> @karato we're waiting for #34 here

@darkled of course, let's wait for #34

**Comment by asaen** [comment]
@longtimeago PR #35 merged, please close the issue if alright

**Comment by longtimeago** [comment]
Thanks!

**Comment by karato** [comment]
@darkled I added **30 mins** to your account, many thanks for working with the project!

added +30 to your rating, now it is equal to [+1722](http://www.netbout.com/b/35091?open=rating)
