### ISSUE TITLE
user can't login or logout

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#201]
unless the credentials switched accounts, release tag 0.3.4 breaks login and logout.

**Comment by ghost** [comment]
@yegor256 let's prioritize this ticket.

**Comment by yegor256** [comment]
@k0r it's a bug in takes: https://github.com/yegor256/takes/issues/144 I'll fix it now

**Comment by ghost** [comment]
@yegor256 thanks.

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.5`

**Comment by ghost** [comment]
@yegor256 it's fixed.

**Comment by ghost** [comment]
@yegor256 thanks.
