### ISSUE TITLE
layout.xsl:101-101: This value is hardcoded for...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#209]
Puzzle `102-3d5e0e72` in `src/main/xsl/layout.xsl:101-101` has to be resolved: This value is hardcoded for now but should be connected to Docs.size() value and present total amount of bytes in user friendly form stored in account. -->... The puzzle was created by Grzegorz Gajos on 26-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by k0r** [comment]
also see [#148](https://github.com/teamed/nerodesk/issues/148)

**Comment by karato** [comment]
@karato since there is no milestone yet I set it to "0.4"

**Comment by k0r** [comment]
@yegor256 let's prioritize this ticket for public beta testing capabilities.

**Comment by k0r** [comment]
#272 fixed this.

**Comment by karato** [comment]
@yegor256 Closed, thanks all
