### ISSUE TITLE
README.md contains broken link

### ISSUE THREAD

**Issue by asaen** [Nerodesk/nerodesk#21]
For the moment `README.md` contains broken link to the image and looks like 
![image](https://cloud.githubusercontent.com/assets/3275813/6345321/f25ecd10-bc15-11e4-8c47-05c9204756f2.png)

**Comment by ggajos** [comment]
@karato it's valid bug

**Comment by karato** [comment]
> @karato it's valid bug

@ggajos thanks, I added the "bug" tag

**Comment by karato** [comment]
this task will get someone's attention soon

**Comment by karato** [comment]
@longtimeago this is your task

**Comment by longtimeago** [comment]
@ggajos Where the missing image is actually located?

**Comment by karato** [comment]
@darkled thanks for the ticket, your account was topped for 15 mins, payment 52445191

**Comment by yegor256** [comment]
@longtimeago there is no such image yet

**Comment by yegor256** [comment]
@k0r do you have a logo in PNG format?

**Comment by ghost** [comment]
@yegor256 http://www.nerodesk.com/logo.png

**Comment by longtimeago** [comment]
Thanks! See PR https://github.com/teamed/nerodesk/pull/29

**Comment by asaen** [comment]
@longtimeago thank you!

**Comment by karato** [comment]
@longtimeago Much obliged! I have added **30 mins** to your account in payment "52512981"... +30 to your rating, your total score is [+2327](http://www.netbout.com/b/35024?open=rating)
