### ISSUE TITLE
AwsDoc.java:52-55: Methods size, type and created...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#210]
Puzzle `101-c6cd25f6` in `src/main/java/com/nerodesk/om/aws/AwsDoc.java:52-55` has to be resolved: Methods size, type and created have to replaced with correct implementation. Size should give number of bytes of the document, type should be MIME type of the document, created should be a timestamp when the document was created.... The puzzle was created by krzyk on 1-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by k0r** [comment]
@yegor256 let's assign this task to @dmzaytsev.

**Comment by yegor256** [comment]
@karato assign @dmzaytsev to this pls

**Comment by karato** [comment]
> @karato assign @dmzaytsev to this pls

@yegor256 yep, done. @dmzaytsev it is your task now

**Comment by dmzaytsev** [comment]
@karato please see PR #291

**Comment by karato** [comment]
> @karato please see PR #291 

@dmzaytsev thanks, I'll take a look

**Comment by dmzaytsev** [comment]
@karato fixed in #291 close this ticket please

**Comment by dmzaytsev** [comment]
@karato fixed in #291 close this ticket please

**Comment by dmzaytsev** [comment]
@karato fixed in #291 close this ticket please

**Comment by yegor256** [comment]
@rultor deploy

**Comment by dmzaytsev** [comment]
@karato fixed in #291 close this ticket please

**Comment by dmzaytsev** [comment]
@yegor256 please pay attention to this ticket
something went wrong here
I fixed the issue ASAP as requested, PR merged 4 days ago
but @karato didn't close the ticket yet

I don't want to be fined for 7 days delay :)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@dmzaytsev it'll be closed soon

**Comment by karato** [comment]
@yegor256 Closed, thanks all

**Comment by karato** [comment]
@dmzaytsev Thanks a lot, I just topped your account for **30 mins**, transaction ID `58550368`, total time was 168 hours and 41 mins... +30 added to your rating, current score is: [+2155](http://www.netbout.com/b/35166?open=rating)
