### ISSUE TITLE
docs.xsl:63-66: Creation date of document should...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#211]
Puzzle `101-20ebe58a` in `src/main/xsl/docs.xsl:63-66` has to be resolved: Creation date of document should be displayed using ISO_8601 combined date time and timezone (e.g. 2007-04-05T12:30-02:00). Right now it is just a unix timestamp.... The puzzle was created by krzyk on 1-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by k0r** [comment]
@yegor256 this is important for presentations.

**Comment by k0r** [comment]
@yegor256 this needs to be fixed asap.

**Comment by yegor256** [comment]
@karato pls assign @dmzaytsev to this issue

**Comment by yegor256** [comment]
@dmzaytsev would be great if you fix this ASAP

**Comment by dmzaytsev** [comment]
@karato please see PR #288

**Comment by k0r** [comment]
@dmzaytsev many thanks.

**Comment by karato** [comment]
> @karato pls assign @dmzaytsev to this issue

@yegor256 done. @dmzaytsev you are assigned to this task. please proceed...

**Comment by karato** [comment]
> @karato please see PR #288 

@dmzaytsev I will take a look, thanks

**Comment by dmzaytsev** [comment]
@karato we may close this task. implemented in #288

**Comment by karato** [comment]
@yegor256 Thanks, closed

**Comment by karato** [comment]
@dmzaytsev thanks, paid, **38 mins** to your account, payment ID is `58197581`, task took 50 hours and 59 mins to complete

there is a bonus for fast delivery (m=3059)

+38 to your rating, your total score is [+1936](http://www.netbout.com/b/35166?open=rating)
