### ISSUE TITLE
user can't create shareable url

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#212]
Current version of README doesn't say anything about creating shortened URLs for sharing files publicly with social media. This is a bug, since this feature is important and will improve usability of the system. Let's modify the README and document this feature. Then, let's implement it and test.

Also see discussion [#191](https://github.com/teamed/nerodesk/issues/191)

**Comment by karato** [comment]
this task will get someone's attention soon

**Comment by karato** [comment]
@alevohin this is your task. the project is currently on pause, please stop working with this task until further notice

**Comment by alevohin** [comment]
@karato please assign someone else

**Comment by karato** [comment]
> @karato please assign someone else

@alevohin someone else will help in this task, no problem at all

**Comment by yegor256** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is urgent

@yegor256 got it, "urgent" tag here

**Comment by karato** [comment]
@darkled do this task

**Comment by karato** [comment]
@darkled we're not on pause any more, you may continue to work with the task

**Comment by yegor256** [comment]
@darkled let's use bit.ly for this

**Comment by yegor256** [comment]
@darkled would be great to complete this in the next 24 hours, otherwise I'll have to assign it to someone else

**Comment by asaen** [comment]
@yegor256 PR #238

**Comment by asaen** [comment]
@karato we're waiting for #238

**Comment by karato** [comment]
> @karato we're waiting for #238 

@darkled agreed, we'll wait for #238

**Comment by asaen** [comment]
@ghost PR #238 merged, please close the issue if alright

**Comment by karato** [comment]
@k0r only @ghost can close this issue, since he opened it

**Comment by k0r** [comment]
when accounts are deleted from GitHub, they're renamed to @ghost. all tickets in this repository authored by @ghost are from my previous account.

**Comment by karato** [comment]
@k0r don't close it, ask @ghost to do do it, since he created it, thanks!

**Comment by k0r** [comment]
@karato you don't seem to understand what @ghost is on GitHub. it's not a real user.

**Comment by yegor256** [comment]
@karato  please close it

**Comment by karato** [comment]
> @karato  please close it

@yegor256 OK, the issue is closed as requested

**Comment by karato** [comment]
@ghost 2 puzzles were created here: `212-00b195c0`/#257, `212-b211119b`

**Comment by karato** [comment]
@darkled thanks, paid, **38 mins** to your account, payment ID is `56423592`, task took 193 hours and 40 mins to complete; there is a bonus for fast delivery (age=2947); +38 to your rating, your total score is [+2143](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@ghost the last puzzle `212-b211119b`/#258 originated from here solved
