### ISSUE TITLE
admins can't conduct system ops

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#213]
Current version of README doesn't say anything about creating an administrative panel for internal system operations. This is a bug, since this feature is important and will improve usability of the system. Let's modify the README and document this feature. Then, let's implement it and test.

**Comment by k0r** [comment]
@yegor256 reformat ticket information if required.

**Comment by yegor256** [comment]
@karato that's definitely a bug, let's dispatch

**Comment by karato** [comment]
> @karato that's definitely a bug, let's dispatch

@yegor256 thanks, I added the "bug" tag

**Comment by karato** [comment]
@longtimeago this is your task... the project is currently on pause, please stop working with this task until further notice

**Comment by karato** [comment]
@k0r since there is no milestone yet I set it to "0.4"

**Comment by karato** [comment]
@longtimeago we're not on pause any more, you may continue to work with the task

**Comment by longtimeago** [comment]
@yegor256 what is "internal system operations"? How we define that use has access to admin panel?
Should I rise new tickets to clarify this?

**Comment by yegor256** [comment]
@longtimeago let's start with something basic and simple. Some users (their URN's should be hard-coded in Java) should have access to `/admin` page, where a full list of all directories in our S3 bucket should be visible. These directory names are URNs of users, so that information will be sufficient to give an admin an understanding of who are using the system now. Later we'll add an ability to do something with these users, but for now a simple listing will be sufficient.

**Comment by longtimeago** [comment]
@karato PR is available for review https://github.com/teamed/nerodesk/pull/234

**Comment by longtimeago** [comment]
@karato waiting for #234

**Comment by karato** [comment]
> @karato waiting for #234

@longtimeago agreed, we'll wait for #234

**Comment by karato** [comment]
@ghost I think we can continue, impediment #234 is closed

**Comment by longtimeago** [comment]
@yegor256 we can close the issue I guess ... finally

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.27`

**Comment by karato** [comment]
@ghost these 2 puzzles were created in this ticket: `213-c0f71aee`, `213-408dfdc6`/#284

**Comment by longtimeago** [comment]
@yegor256 can we close the issue?

**Comment by yegor256** [comment]
@longtimeago yes, thanks!

**Comment by karato** [comment]
@yegor256 please don't close it.. @ghost could you please close it, if it is done?

**Comment by k0r** [comment]
@karato please stop asking @ghost to close issues. it's a deleted account, not a contributor on the project. this has been explained to you several times now.

**Comment by yegor256** [comment]
@karato close it yourself pls

**Comment by longtimeago** [comment]
@yegor256 karato needs to be upgraded, he is too slow :)

**Comment by karato** [comment]
> @karato close it yourself pls

@yegor256 issue closes as you just asked

**Comment by karato** [comment]
@longtimeago Many thanks! **38 mins** were added to your account in Transaction ID `58090907` (task took 172 hours and 43 mins)... age=2947, that's why a bonus here for fast delivery... +38 added to your rating, at the moment it is: [+4170](http://www.netbout.com/b/35024?open=rating)
