### ISSUE TITLE
user can't share files publicly 

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#214]
Current version of README doesn't say anything about sharing files publicly. This is a bug, since this feature is important and will improve usability of the system. Let's modify the README and document this feature. Then, let's implement it and test.

Also see discussions [#191](https://github.com/teamed/nerodesk/issues/191) and [#212](https://github.com/teamed/nerodesk/issues/212)

**Comment by karato** [comment]
I am aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@longtimeago do this task

**Comment by longtimeago** [comment]
@karato  please assign someone else

**Comment by karato** [comment]
> @karato  please assign someone else

@longtimeago got it, someone else will be assigned soon

**Comment by karato** [comment]
@carlosmiranda this is your task... we're on pause in the project, please stop working with this, until further information

**Comment by carlosmiranda** [comment]
@karato @yegor256 Am I supposed to work on this now?

**Comment by yegor256** [comment]
@carlosmiranda I'll let you know soon. for now we're still on hold.

**Comment by carlosmiranda** [comment]
@yegor256 All right, thanks for letting me know.

**Comment by carlosmiranda** [comment]
@karato Please give us more time

**Comment by karato** [comment]
> @karato Please give us more time

@carlosmiranda OK, take your time

**Comment by karato** [comment]
@carlosmiranda the project is back on track, please continue

**Comment by yegor256** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is urgent

@yegor256 right, I added "urgent" tag

**Comment by carlosmiranda** [comment]
@yegor256 Please see PR #235.

**Comment by yegor256** [comment]
@carlosmiranda would be great to see some code here as well

**Comment by carlosmiranda** [comment]
@yegor256 Right, I added some stub implementations to #235.

**Comment by carlosmiranda** [comment]
@yegor256 may we close it now? #235 has been merged.

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by karato** [comment]
@yegor256 please don't close it.. @ghost could you please close it, if it is done?

**Comment by yegor256** [comment]
@karato close it please yourself, the `@ghost` is not longer in the project

**Comment by karato** [comment]
> @karato close it please yourself, the `@ghost` is not longer in the project

@yegor256 issue closes as you just asked

**Comment by karato** [comment]
@ghost once `214-e6cb8df9`/#243 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by karato** [comment]
@carlosmiranda Much appreciated! **38 mins** was added to your account, payment ID `56006982`, time spent is 89 hours and 24 mins... the bonus for fast delivery (age=2881)... +38 to your rating, your total score is [+4732](http://www.netbout.com/b/35023?open=rating)

**Comment by karato** [comment]
@ghost last puzzled solved `243-313457d9`/#256
