### ISSUE TITLE
TkAppTest.java:76-79: Test readsFileWithSpecialCharactersInName and deletesFileWithSpecialCharactersInName are...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#215]
Puzzle `160-88061572` in `src/test/java/com/nerodesk/takes/TkAppTest.java:76-79` has to be resolved: Test readsFileWithSpecialCharactersInName and deletesFileWithSpecialCharactersInName are disabled because of a bug in takes 0.11.2, when yegor256/takes#126 is resolved and a new takes with this fix is released add it to the pom.xml and uncomment those tests.... The puzzle was created by krzyk on 4-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@krzyk this is your task

**Comment by krzyk** [comment]
@karato PR #222

**Comment by karato** [comment]
@krzyk the project is currently on pause, please stop working with this task until further notice

**Comment by karato** [comment]
@krzyk the project is back on track, please continue

**Comment by karato** [comment]
@yegor256 Done, thanks all, closing..

**Comment by karato** [comment]
@krzyk thanks, I just added **38 mins** to your account, payment `55992771`, 68 hours and 46 mins spent

the bonus for fast delivery (age=3018)

+38 to your rating, your total score is [+5329](http://www.netbout.com/b/35035?open=rating)
