### ISSUE TITLE
login page update

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#216]
Let's update the login page with social media icons instead of a login link, and let's update the non-logo font to [Play](https://www.google.com/fonts/specimen/Play).

Example:
![login update](http://www.nerodesk.com/nd_login_update_4.jpg)

**Comment by ghost** [comment]
@yegor256 updated.

**Comment by ghost** [comment]
@yegor256 let's prioritize this ticket.

**Comment by yegor256** [comment]
@karato it's a valid bug, please dispatch it

**Comment by karato** [comment]
> @karato it's a valid bug, please dispatch it

@yegor256 thanks, I added the "bug" tag

**Comment by ghost** [comment]
updated image.

**Comment by karato** [comment]
@carlosmiranda do this task

**Comment by carlosmiranda** [comment]
@karato Assign someone else please, too busy at the moment

**Comment by karato** [comment]
> @karato Assign someone else please, too busy at the moment

@carlosmiranda I will try to find someone else

**Comment by karato** [comment]
@longtimeago this is your task

**Comment by longtimeago** [comment]
@karato project is on hold now

**Comment by longtimeago** [comment]
@karato assign someone else please

**Comment by karato** [comment]
> @karato project is on hold now

@longtimeago OK, take your time

**Comment by karato** [comment]
> @karato assign someone else please

@longtimeago no problem, I will try to find somebody else

**Comment by karato** [comment]
@caarlos0 this is your task

**Comment by caarlos0** [comment]
@karato assign someone else, please, too busy right now.

**Comment by karato** [comment]
> @karato assign someone else, please, too busy right now.

@caarlos0 I will ask somebody else to pick this up

**Comment by karato** [comment]
@ggajos this is your task

**Comment by ghost** [comment]
updated.

**Comment by ggajos** [comment]
@karato this project is on hold still right?

**Comment by karato** [comment]
> @karato this project is on hold still right?

@ggajos sure, take your time, I know about this pause

**Comment by yegor256** [comment]
@ggajos yes, it's still on hold, I'll update you soon

**Comment by yegor256** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is urgent

@yegor256 thanks, I added the "urgent" tag

**Comment by yegor256** [comment]
@karato assign me to this task please, @ggajos hope you don't mind

**Comment by karato** [comment]
> @karato assign me to this task please, @ggajos hope you don't mind

@yegor256 sure, the ticket is yours, go ahead

**Comment by yegor256** [comment]
@kory PR is here: #229

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.11`

**Comment by yegor256** [comment]
@rultor hello

**Comment by yegor256** [comment]
@kory please close this ticket

**Comment by kory** [comment]
@yegor256, I believe you have the wrong @user, I'm getting emails every time you use @kory.

**Comment by yegor256** [comment]
@Kory sorry, my fault.

**Comment by yegor256** [comment]
@karato please close this task as completed

**Comment by karato** [comment]
> @karato please close this task as completed

@yegor256 OK, sure, closing
