### ISSUE TITLE
No PDD restrictions

### ISSUE THREAD

**Issue by asaen** [Nerodesk/nerodesk#22]
For the moment there are no `.pdd` restrictions defined. Do we need this file to define `min-` and `max-estimate`, `min-words`, etc?

**Comment by yegor256** [comment]
we need to have this `.pdd` file in the root directory:

```
--source=.
--verbose
--rule min-words:20
--rule min-estimate:15
--rule max-estimate:90

```

**Comment by ggajos** [comment]
It's already done in #23

**Comment by asaen** [comment]
@ggajos right, the issue was created before
