### ISSUE TITLE
TkDir.java:49-52: This is initial implementation and...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#221]
Puzzle `150-9049471a` in `src/main/java/com/nerodesk/takes/doc/TkDir.java:49-52` has to be resolved: This is initial implementation and is not doing anything useful yet. We should implement ability to create directories here. Moreover there should be also way to edit them, remove and attach existing documents.... The puzzle was created by Grzegorz Gajos on 7-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@pinaf this is your task

**Comment by pinaf** [comment]
@karato see PR #300

**Comment by karato** [comment]
> @karato see PR #300

@pinaf thank you, I will check it

**Comment by pinaf** [comment]
@karato we're waiting for #299 here

**Comment by karato** [comment]
> @karato we're waiting for #299 here

@pinaf yes, of course, we'll wait for #299

**Comment by karato** [comment]
@yegor256 we waited for #299, it is closed already

**Comment by pinaf** [comment]
@yegor256 so what do I do here?

**Comment by pinaf** [comment]
@karato I need more time here

**Comment by karato** [comment]
> @karato I need more time here

@pinaf agreed, take your time

**Comment by yegor256** [comment]
@karato it's postponed

**Comment by karato** [comment]
> @karato it's postponed

@yegor256 thanks, I added the "postponed" tag

**Comment by karato** [comment]
> @karato it's postponed

@yegor256 OK, I will try to assign someone else

**Comment by pinaf** [comment]
@karato fixed

**Comment by karato** [comment]
@yegor256 2 puzzles were created here: `221-2a7d335c`/#314, `221-b3fea3d5`

**Comment by karato** [comment]
@yegor256 The issue is closed

**Comment by pinaf** [comment]
@yegor256 @karato closed 4 days ago

**Comment by pinaf** [comment]
@yegor256 this one was never paid. is that because it is postponed?

**Comment by yegor256** [comment]
@pinaf yeah, you fixed it after it was postponed (and you were un-assigned)

**Comment by pinaf** [comment]
@yegor256 well the PR was created on may 28th and you guys decided to postpone it after I had done the work...

**Comment by yegor256** [comment]
@karato please add extra 30 mins to @pinaf here

**Comment by pinaf** [comment]
@yegor256 thank you

**Comment by karato** [comment]
> @karato please add extra 30 mins to @pinaf here

@yegor256 I've paid 30 mins to @pinaf in transaction `AP-03J746806E340360K`
