### ISSUE TITLE
broken SVG images

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#230]

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.12`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.13`

**Comment by karato** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@yegor256 your task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 Thanks a lot, I just topped your account for **45 mins**, transaction ID `000-78ed88db`, total time was 59 mins... age=26 hours and 56 mins, that's why a bonus here for fast delivery... +45 added to your rating, at the moment it is: [+9200](http://www.netbout.com/b/35008?open=rating)
