### ISSUE TITLE
big files cause out-of-memory errors on Heroku

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#231]

**Comment by yegor256** [comment]
@k0r I can't reproduce the bug, since facebook login doesn't work :(

**Comment by karato** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by yegor256** [comment]
@karato pls set milestone to 0.4

**Comment by karato** [comment]
@yegor256 do this task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 many thanks for the bug report, I added 15 mins to your acc, transaction `000-7803cafa`

**Comment by karato** [comment]
> @karato pls set milestone to 0.4

@yegor256 milestone set to `0.4`, thanks

**Comment by longtimeago** [comment]
@yegor256 you can reproduce it if just run app in dev mode and try to upload big file

**Comment by yegor256** [comment]
@longtimeago I fixed it in PR #233

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.15`

**Comment by yegor256** [comment]
@k0r try to upload a big file pls. But keep in mind that the maximum size is 250mb

**Comment by karato** [comment]
@yegor256 thanks, I just added **30 mins** to your account, payment `000-40403838`, 63 hours and 52 mins spent; +30 added to your rating, current score is: [+9292](http://www.netbout.com/b/35008?open=rating)
