### ISSUE TITLE
Exception on uploading when no file specified (dev mode)

### ISSUE THREAD

**Issue by longtimeago** [Nerodesk/nerodesk#232]
Given fresh start in dev mode
And no file chosen for upload
When push submit button
Then
![screenshot from 2015-04-22 20 25 01](https://cloud.githubusercontent.com/assets/1388994/7280753/b13f0f3a-e92d-11e4-891c-838177d927fd.png)
And in traces:

```
java.lang.IllegalArgumentException: /tmp/1429723070896-0/urn/test/1/1 does not exist
        at org.apache.commons.io.FileUtils.sizeOf(FileUtils.java:2413)
        at com.nerodesk.om.mock.MkDoc.size(MkDoc.java:97)
        at com.nerodesk.om.SmallDoc.size(SmallDoc.java:89)
        at com.nerodesk.takes.TkDocs.list(TkDocs.java:110)
        at com.nerodesk.takes.TkDocs.access$000(TkDocs.java:56)
        at com.nerodesk.takes.TkDocs$1.toXembly(TkDocs.java:81)
```

After that app is not able to recover at all. All subsequent calls to `http://localhost:8080/` resulting to the same error.

**Comment by k0r** [comment]
@yegor256 this is important for presentations.

**Comment by k0r** [comment]
@yegor256 this needs to be fixed asap.

**Comment by yegor256** [comment]
@karato pls assign @dmzaytsev to this problem

**Comment by dmzaytsev** [comment]
@karato please see PR #289

**Comment by k0r** [comment]
@dmzaytsev many thanks.

**Comment by dmzaytsev** [comment]
@longtimeago the PR #289 has been merged. Could you close the task please ?

**Comment by dmzaytsev** [comment]
@longtimeago sorry, I don't understand how I closed this ticket

please close it if alright

**Comment by longtimeago** [comment]
@dmzaytsev yep, thank you very much!
