### ISSUE TITLE
No content length specified for S3 upload

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#240]
```
com.amazonaws.services.s3.AmazonS3Client: No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
```

let's fix this, to get rid of potential out-of-memory errors on big file uploads

**Comment by yegor256** [comment]
@karato pls assign @krzyk to this issue

**Comment by karato** [comment]
@yegor256 I will ask someone to take care of this task soon

**Comment by karato** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by yegor256** [comment]
@karato pls set milestone to 0.4

**Comment by karato** [comment]
@carlosmiranda this is your task

**Comment by karato** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-fb475bb3

**Comment by karato** [comment]
> @karato pls assign @krzyk to this issue

@yegor256 OK. @krzyk the ticket is yours, please proceed

**Comment by karato** [comment]
> @karato pls set milestone to 0.4

@yegor256 I attached this issue to milestone `0.4`

**Comment by krzyk** [comment]
@yegor256 PR #246

**Comment by krzyk** [comment]
@yegor256 if the code changes in master fix the problem, please close this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by karato** [comment]
@krzyk Thanks for your contribution, **30 mins** was added to your account, payment ID is `56385955`, 68 hours and 57 mins spent total

+30 added to your rating, at the moment it is: [+5086](http://www.netbout.com/b/35035?open=rating)
