### ISSUE TITLE
UI links are not rendered in HTML

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#241]
UI links in TkDocs (`read`, `delete`, etc.) are not rendered correctly, since `docs.xsl` is using incorrect XML elements, which were correct before the refactoring of #233 

Let's create a test that should render the page into HTML and then check the presence of links inside it, using XPath.  Then, let's fix.

**Comment by yegor256** [comment]
@karato pls assign @krzyk to this issue

**Comment by karato** [comment]
@yegor256 we will find someone to do this task, soon

**Comment by karato** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by karato** [comment]
> @karato pls assign @krzyk to this issue

@yegor256 OK @krzyk please start, the task is yours

**Comment by karato** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-5ee0766d`

**Comment by krzyk** [comment]
@yegor256 PR #245

**Comment by krzyk** [comment]
@karato we're waiting for #245

**Comment by karato** [comment]
> @karato we're waiting for #245 

@krzyk yep, got it, let's wait for #245 being solved

**Comment by k0r** [comment]
@yegor256 let's prioritize this ticket for public beta testing capabilities.

**Comment by k0r** [comment]
@yegor256 completing this ticket will also improve testing #252 #263

**Comment by karato** [comment]
@yegor256 FYI, issue #245 is already closed, and we were waiting for it..

**Comment by krzyk** [comment]
@yegor256 please close this issue, it has been merged to master

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.19`

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.19`

**Comment by yegor256** [comment]
@rultor hello

**Comment by k0r** [comment]
@yegor256 page displays `error on line 1 at column 1: Document is empty`

**Comment by yegor256** [comment]
@k0r yep, that's because bit.ly is not configured... please, create a ticket about it, I'll configure and fix the issue

**Comment by yegor256** [comment]
@krzyk works fine now, thanks!

**Comment by karato** [comment]
@krzyk I just added **45 mins** to your account, many thanks for your contribution.. 56824390 spent here

the bonus for fast delivery (age=42 hours and 21 mins)

+45 added to your rating, current score is: [+4871](http://www.netbout.com/b/35035?open=rating)
