### ISSUE TITLE
TkSetVisibility.java:45-51: Let's implement the setting of...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#243]
Puzzle `214-e6cb8df9` in `src/main/java/com/nerodesk/takes/doc/TkSetVisibility.java:45-51` has to be resolved: Let's implement the setting of file visibility. When a request is received by this Take, it should read the appropriate parameters from the request, and set the permissions of the associated Doc accordingly. The parameter "visibility" should determine whether the file is private or public. Note that we don't have this functionality in the Doc API yet, either, so you may want to start with a skeleton of that - use PDD to your advantage.... The puzzle was created by Carlos Miranda on 24-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@pinaf this is your task

**Comment by karato** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by yegor256** [comment]
@karato please set milestone to 0.4

**Comment by karato** [comment]
> @karato please set milestone to 0.4

@yegor256 I attached this issue to milestone `0.4`

**Comment by pinaf** [comment]
@karato please assign someone else here

**Comment by yegor256** [comment]
@karato assign @krzyk to this one pls

**Comment by karato** [comment]
> @karato please assign someone else here

@pinaf 30 points was deducted from your rating

**Comment by karato** [comment]
> @karato please assign someone else here

@pinaf someone else will help in this task, no problem at all

**Comment by karato** [comment]
> @karato assign @krzyk to this one pls

@yegor256 of course! @krzyk it's your ticket now, please go ahead

**Comment by krzyk** [comment]
@karato PR #247

**Comment by krzyk** [comment]
@karato PR #254 (I forgot to remove todo in the previous one)

**Comment by karato** [comment]
@yegor256 these 2 puzzles were created in this ticket: `243-313457d9`, `243-21f91001`/#255

**Comment by karato** [comment]
@yegor256 Closing this issue now...

**Comment by karato** [comment]
@krzyk thank you, added **30 mins** to your acc, payment num is `56448616`, 127 hours and 30 mins spent in total to complete. added +30 to your rating, now it is equal to [+4864](http://www.netbout.com/b/35035?open=rating)

**Comment by karato** [comment]
@yegor256 the last puzzle `243-313457d9`/#256 originated from here solved
