### ISSUE TITLE
move repository to new Github account

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#244]
Let's move it to `nerodesk` account

**Comment by karato** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by karato** [comment]
@yegor256 do this task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-7d572718

**Comment by yegor256** [comment]
done

**Comment by karato** [comment]
@yegor256 **30 mins** added to your account (payment number `000-5934cef0`), many thanks for your contribution! 240 hours and 49 mins spent here.; +30 added to your rating, current score is: [+9238](http://www.netbout.com/b/35008?open=rating)
