### ISSUE TITLE
Incomplete documentation: how to start the application

### ISSUE THREAD

**Issue by asaen** [Nerodesk/nerodesk#25]
Let's add information about executing the application into `README.md`. For the moment the application is executed by

```
java -jar target\nerodesk-jar-with-dependencies.jar port
```

**Comment by ggajos** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@ggajos right, I added the `bug` tag

**Comment by karato** [comment]
I will find a developer for the task soon...

**Comment by karato** [comment]
@ggajos this is your task

**Comment by karato** [comment]
@darkled thanks a lot for reporting, **15 mins** added to your acc, pmt ID `52442227`

**Comment by ggajos** [comment]
@darkled you can see pull request above that is fixing this issue, if that's all here please close.

**Comment by asaen** [comment]
@ggajos thank you!

**Comment by karato** [comment]
@ggajos Thanks a lot, I just topped your account for **30 mins**, transaction ID `AP-44W0034150857560R`; added +30 to your rating, now it is equal to [+1989](http://www.netbout.com/b/35094?open=rating)
