### ISSUE TITLE
deployment to heroku is broken

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#251]
We can't deploy to heroku any more, since they changed the version or Ruby. Our sass maven plugin is conflicting with them.

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.16`

**Comment by karato** [comment]
@yegor256 attached this issue to milestone "0.6" (let me know if this is wrong)

**Comment by karato** [comment]
@yegor256 your task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-59e880fe

**Comment by yegor256** [comment]
fixed

**Comment by karato** [comment]
@yegor256 thank you, added **30 mins** to your acc, payment num is `000-900c67da`, 53 hours and 2 mins spent in total to complete

+30 added to your rating, current score is: [+9215](http://www.netbout.com/b/35008?open=rating)
