### ISSUE TITLE
TkSetVisibility.java:52-55: Implement setting of document visibility...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#255]
Puzzle `243-21f91001` in `src/main/java/com/nerodesk/takes/doc/TkSetVisibility.java:52-55` has to be resolved: Implement setting of document visibility using method `show` from `Attributes`. Update docs.xsl and TkDocs with correct link to this class. docs.xsl should also show the current state of document public/private status (using `Attributes.visible` method).... The puzzle was created by krzyk on 26-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@yegor256 I added milestone `0.6` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@pinaf do this task

**Comment by pinaf** [comment]
@karato please see PR #277

**Comment by karato** [comment]
> @karato please see PR #277

@pinaf thank you, I will check it

**Comment by pinaf** [comment]
@karato fixed!

**Comment by karato** [comment]
@yegor256 there is a puzzle in this code `255-bf924f1e`/#278, we'll resolve it later

**Comment by karato** [comment]
@yegor256 Thanks, closing it now.

**Comment by karato** [comment]
@pinaf **30 mins** added to your account (payment number `AP-5JA90898Y5108981G`), many thanks for your contribution! 149 hours and 17 mins spent here.. +30 added to your rating, at the moment it is: [+7575](http://www.netbout.com/b/35128?open=rating)

**Comment by karato** [comment]
@yegor256 the last puzzle `255-bf924f1e`/#278 originated from here solved
