### ISSUE TITLE
AwsAttributes.java:44-46: Implement storage and retrieval of...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#256]
Puzzle `243-313457d9` in `src/main/java/com/nerodesk/om/aws/AwsAttributes.java:44-46` has to be resolved: Implement storage and retrieval of visible status of the document, by implementing methods `visible` and `show` below. Don't forget to test it first.... The puzzle was created by krzyk on 26-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@yegor256 I added milestone `0.6` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@darkled do this task

**Comment by asaen** [comment]
@karato we're waiting for #282

**Comment by karato** [comment]
> @karato we're waiting for #282 

@darkled right, let's wait for #282

**Comment by asaen** [comment]
@karato assign someone else here please

**Comment by karato** [comment]
> @karato assign someone else here please

@darkled deducted 30 from your rating :(

**Comment by karato** [comment]
> @karato assign someone else here please

@darkled right, I will find someone else, no problem

**Comment by karato** [comment]
@yegor256 I think we can continue, impediment #282 is closed

**Comment by karato** [comment]
@longtimeago do this task

**Comment by longtimeago** [comment]
@karato PR https://github.com/Nerodesk/nerodesk/pull/292 is waiting for review

**Comment by longtimeago** [comment]
@karato PR was merged. Please, close the issue

**Comment by karato** [comment]
@yegor256 Thanks all, I am closing

**Comment by karato** [comment]
@longtimeago thank you, added **38 mins** to your acc, payment num is `58197593`, 48 hours spent in total to complete

there is a bonus for fast delivery (m=2880)

+38 to your rating, your total score is [+4271](http://www.netbout.com/b/35024?open=rating)
