### ISSUE TITLE
Doc.java:85-87: Method `shortUrl` should be executed...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#257]
Puzzle `212-00b195c0` in `src/main/java/com/nerodesk/om/Doc.java:85-87` has to be resolved: Method `shortUrl` should be executed from a proper place on the UI in order to provide sharing short links functionality for users.... The puzzle was created by Alexey Saenko on 23-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@pinaf this is your task

**Comment by karato** [comment]
@yegor256 there is no milestone yet, so I set it to `0.4`

**Comment by pinaf** [comment]
@karato please see PR #262

**Comment by karato** [comment]
> @karato please see PR #262

@pinaf will take a look, thanks

**Comment by pinaf** [comment]
@karato fixed!

**Comment by karato** [comment]
@yegor256 Closing this issue now...

**Comment by karato** [comment]
@pinaf Many thanks! **30 mins** were added to your account in Transaction ID `AP-7CL85627UC769562X` (task took 142 hours and 11 mins)... +30 added to your rating, current score is: [+7600](http://www.netbout.com/b/35128?open=rating)
