### ISSUE TITLE
AwsDoc.java:137-141: Implementation has to be replaced...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#258]
Puzzle `212-b211119b` in `src/main/java/com/nerodesk/om/aws/AwsDoc.java:137-141` has to be resolved: Implementation has to be replaced with the correct one using the correct authentication for the bit.ly data and the correctly generated url to the actual document. After that fix and un-ignore the test `com.nerodesk.om.aws.AwsDocTest.shortenUrl()` to match some real data.... The puzzle was created by Alexey Saenko on 23-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@caarlos0 do this task

**Comment by karato** [comment]
@yegor256 I set milestone here to `0.4`, let me know if it is wrong

**Comment by yegor256** [comment]
@caarlos0 our user name for Bit.ly is `Nerodesk`. To get API token you can use `${bitly.key}` available during Maven build (same way as we're using `${fb.app}`, for example, see `MANIFEST.MF`)

**Comment by yegor256** [comment]
@caarlos0 this is rather urgent, please do it asap. thanks!

**Comment by k0r** [comment]
@yegor256 is there a way to restore site accessibility until this is fixed?

**Comment by yegor256** [comment]
@k0r yeah, will release now

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.20`

**Comment by k0r** [comment]
@yegor256 site still isn't accessible with `0.3.20` source contains `BitlyException: INVALID_LOGIN`

**Comment by k0r** [comment]
@yegor256 site inaccessible with `0.3.20` source contains `BitlyException: INVALID_LOGIN`

**Comment by yegor256** [comment]
@k0r hm.. that's strange... let me check bit.ly credentials

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.21`

**Comment by yegor256** [comment]
@k0r seems to be working now

**Comment by yegor256** [comment]
@caarlos0 as you see, I hard-coded our production bit.ly credentials, which is a wrong approach, and a very temporary one. Please, redesign it asap so that credentials come into MANIFEST.MF during Maven build

**Comment by k0r** [comment]
@yegor256 thanks.

**Comment by caarlos0** [comment]
@k0r @yegor256 @karato Working on it...

**Comment by k0r** [comment]
@yegor256 we should consider #264, as the bit.ly generated urls should redirect to the file information page where the takes url to the file location on aws can be read, rather than directly linking bit.ly to the file without first going to the file information page.

**Comment by k0r** [comment]
@yegor256 directly linking bit.ly to the file was the idea at first, but it's been updated.

**Comment by caarlos0** [comment]
@k0r @yegor256 @karato sorry, I'm with some trouble on my environment here (internet access). I'm aware this issue is urgent, so I'll ask to assign to someone else in case I don't get this fixed soon...

sorry

**Comment by caarlos0** [comment]
@karato please assign to someone else

**Comment by karato** [comment]
> @karato please assign to someone else

@caarlos0 30 points deducted from your rating

**Comment by karato** [comment]
> @karato please assign to someone else

@caarlos0 got it, someone else will be assigned soon

**Comment by yegor256** [comment]
@karato assign @darkled  to this pls

**Comment by karato** [comment]
> @karato assign @darkled  to this pls

@yegor256 done, @darkled is a new assignment at the task, please go on. whoever worked with this task before, please stop right now

**Comment by asaen** [comment]
@karato we're waiting for #281

**Comment by karato** [comment]
> @karato we're waiting for #281 

@darkled right, let's wait for #281

**Comment by karato** [comment]
@yegor256 Issue #281 is already closed (we were waiting for it) Maybe we can continue..

**Comment by asaen** [comment]
@karato PR #281 merged, please close the issue if alright

**Comment by k0r** [comment]
@yegor256 site inaccessible with `0.3.27` source contains `bitlyj.BitlyException: INVALID_LOGIN`. 

same thing that happened [here](https://github.com/Nerodesk/nerodesk/issues/258#issuecomment-99197367).

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.28`

**Comment by yegor256** [comment]
@k0r should be fine now

**Comment by karato** [comment]
@yegor256 Done, the task is closed

**Comment by karato** [comment]
@darkled Thanks so much! Your account was topped up for **45 mins** (transaction ID is `57661361`, the task took 25 hours and 2 mins); m=1502, that's why a bonus here for fast delivery; added +45 to your rating, now it is equal to [+2017](http://www.netbout.com/b/35091?open=rating)
