### ISSUE TITLE
The system should be able to upload/download and delete files in S3

### ISSUE THREAD

**Issue by ggajos** [Nerodesk/nerodesk#26]
Currently we have no notion of S3. Let's fix that. Implement another version of `Storage` interface that will use Amazon S3.

We might use http://s3.jcabi.com/ for that purpose.

**Comment by ggajos** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@ggajos right, I added the `bug` tag

**Comment by karato** [comment]
I will ask someone to take care of this task soon

**Comment by karato** [comment]
@pinaf this is your task

**Comment by karato** [comment]
@ggajos many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-2A5566406U402210H`

**Comment by pinaf** [comment]
@karato please assign to someone else

**Comment by karato** [comment]
> @karato please assign to someone else

@pinaf I will try to find someone else

**Comment by karato** [comment]
@darkled this is your task

**Comment by asaen** [comment]
@ggajos PR #45 merged, please close the issue if alright

**Comment by karato** [comment]
@darkled Thanks a lot, I just topped your account for **30 mins**, transaction ID `52938126`; +30 added to your rating, at the moment it is: [+1782](http://www.netbout.com/b/35091?open=rating)
