### ISSUE TITLE
heroku application error

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#263]
uploading a file of any size causes a Heroku application error. to replicate, upload a file of any size with any browser.

related tickets: #242 #251 #253

**Comment by k0r** [comment]
@yegor256 let's prioritize this ticket or related tickets that could be causing this error for public beta testing capabilities.

**Comment by yegor256** [comment]
@k0r this is what I see in logs:

```
sock=backend at=error code=H18 desc="Request Interrupted" method=POST 
path="/doc/write" host=beta.nerodesk.com 
request_id=1c4ce399-2ea7-4ac0-a8c3-579c038aaf67 fwd="50.201.186.106" 
dyno=web.1 connect=1ms service=428ms status=503 bytes=473
```

And that's it. No exceptions. No idea why it's happening... investigating now.

**Comment by yegor256** [comment]
@k0r this is what Heroku says about H18 error: "Either the client socket or backend (your app’s web process) socket was closed before the backend returned an HTTP response. The sock field in the log has the value client or backend depending on which socket was closed." see https://devcenter.heroku.com/articles/error-codes#h18-request-interrupted

**Comment by yegor256** [comment]
@k0r and this is happening not every time. Sometimes I can upload a file without problems. I think I know what's going on...

**Comment by k0r** [comment]
@yegor256 tested again and got the same result.

**Comment by yegor256** [comment]
@k0r this seems to be the problem: https://github.com/yegor256/takes/issues/242 working on it now

**Comment by yegor256** [comment]
@k0r try to upload a very small file (1Kb), you won't have an error. The problem happens when the file is long enough so that Heroku drops connection with our app

**Comment by k0r** [comment]
@yegor256 same result with a 1mb file.

**Comment by yegor256** [comment]
@k0r try 1Kb file

**Comment by k0r** [comment]
@yegor256 works.

**Comment by yegor256** [comment]
@k0r yeah, the problem is in the size of the file... and it has something to do with heroku... I'm looking into it now

**Comment by yegor256** [comment]
@k0r this is what I see in logs:

```
2015-05-02T02:37:32.090250+00:00 heroku[router]: sock=backend at=error code=H18 desc="Request Interrupted" method=POST path="/doc/write" host=beta.nerodesk.com request_id=5d8507ac-66d5-4919-a824-1f34f2bba521 fwd="50.201.186.106" dyno=web.1 connect=1ms service=319ms status=503 bytes=473
2015-05-02T02:37:32.058120+00:00 app[web.1]: d88224f com.nerodesk.om.aws.AwsDoc: com.jcabi.s3.retry.ReOcket@82bf62fd written
```

This means that we interrupt the request and then immediately after that save the file to S3...

**Comment by karato** [comment]
@yegor256 your task, 30 mins is budget

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.18`

**Comment by yegor256** [comment]
@k0r try now. I can upload files of any size, but those that are bigger than ~100Mb take too much time and heroku sometimes drops connection. It's a known issue in Takes: https://github.com/yegor256/takes/issues/248 I'm not yet sure it's possible to resolve it.. Maybe we'll have to find some workaround.

**Comment by k0r** [comment]
@yegor256 can't login: `oops, something went wrong! java.lang.AssertionError: HTTP response status is not equal to 200: 400 Bad Request`

**Comment by k0r** [comment]
@yegor256 nearly 3 months of development the only thing that works is logging in with facebook.

**Comment by yegor256** [comment]
@k0r confirm, there is a bug in takes: https://github.com/yegor256/takes/issues/249 (fixing now)

**Comment by yegor256** [comment]
@k0r should be fine now, try again

**Comment by k0r** [comment]
@yegor256 same thing.

**Comment by k0r** [comment]
@yegor256 logging in is fixed.

**Comment by yegor256** [comment]
@k0r please elaborate on "same thing". what exactly are you doing and what is happening?

**Comment by k0r** [comment]
@yegor256 logging in is fixed.

**Comment by k0r** [comment]
@yegor256 `oops, something went wrong!
org.takes.HttpException: GET http://beta.nerodesk.com/doc/write`

**Comment by yegor256** [comment]
@k0r what file size you're trying to upload?

**Comment by k0r** [comment]
@yegor256 that was from a 150mb file.

**Comment by yegor256** [comment]
@k0r yeah, that's too much for now. I think everything below 50Mb should work fine. Try something smaller, below 50Mb

**Comment by k0r** [comment]
@yegor256 50mb uploads without a problem.

**Comment by yegor256** [comment]
@k0r yes, that's what I'm saying... I'm not yet sure whether this problem is solvable in general. we have to go through a 10-million byte stream and find the location of a string that stops the file content. that's what takes time... I'll think about some optimization in https://github.com/yegor256/takes/issues/248

**Comment by k0r** [comment]
@yegor256 this means that editable per file limit parameters isn't currently possible with takes.

**Comment by yegor256** [comment]
@k0r I think we can close this ticket, right?

**Comment by k0r** [comment]
@yegor256 thanks.

**Comment by karato** [comment]
@yegor256 Many thanks! **30 mins** were added to your account in Transaction ID `000-8f26d565` (task took 725 hours and 13 mins); +30 added to your rating, current score is: [+6991](http://www.netbout.com/b/35008?open=rating)
