### ISSUE TITLE
readme.md requires copyright information

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#268]
readme.md should contain the copyright notice. read [this](http://www.yegor256.com/2015/05/04/how-to-protect-business-idea.html) post for more information.

**Comment by yegor256** [comment]
@k0r fixed

**Comment by k0r** [comment]
@yegor256 just the `Copyright (c) 2015, nerodesk.com All rights reserved` information is sufficient. all of the other information is in `license.txt`

**Comment by yegor256** [comment]
@k0r fixed

**Comment by k0r** [comment]
@yegor256 thanks.
