### ISSUE TITLE
bit.ly links return 404 not found

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#270]
links should point to beta.nerodesk.com instead of www.nerodesk.com for /doc/read?file=

**Comment by k0r** [comment]
@rultor hello

**Comment by k0r** [comment]
@rultor release, tag is `0.3.22`

**Comment by yegor256** [comment]
@k0r did you make any changes to the code? If yes, what is the commit hash?

**Comment by k0r** [comment]
@yegor256 yes.

**Comment by k0r** [comment]
@yegor256 [here](https://github.com/Nerodesk/nerodesk/commit/8f3113bf0ffb234cd6432bf5f644be3f14f621b5)

**Comment by yegor256** [comment]
@k0r when you make changes, make sure your commit messages start with the ticket number they are related to, just like I'm doing, see: https://github.com/Nerodesk/nerodesk/commits/master This way Github will link them automatically to the ticket

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.22`

**Comment by k0r** [comment]
@yegor256 sure thing.

**Comment by k0r** [comment]
@yegor256 thanks for the confirmation.
