### ISSUE TITLE
Github access permissions are broken

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#271]
Github team was deleted and access credentials revoked (I believe, accidentally). This has to be restored.

**Comment by k0r** [comment]
@yegor256 a team wasn't deleted.

**Comment by yegor256** [comment]
@k0r yes it was. there was a team called `nerodesk`. now it's gone.

**Comment by k0r** [comment]
@yegor256 it's been that way for a while.

**Comment by yegor256** [comment]
@k0r this is what has to be done:
1. team `Contributors` has to be renamed to `nerodesk`
2. all project participants have to added to that team, including @karato
3. team description has to be set to `alive; tech=java`

**Comment by k0r** [comment]
@yegor256 fixed.

**Comment by k0r** [comment]
@yegor256 fixed.

**Comment by k0r** [comment]
@yegor256 everything good here?

**Comment by karato** [comment]
@yegor256 attached this issue to milestone "0.7" (let me know if this is wrong)

**Comment by k0r** [comment]
@karato the milestone 0.7 is used for planning and future implementations, not tickets that are resolved quickly.

**Comment by karato** [comment]
@yegor256 do this task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 thanks for this bug, I topped your account for 15 mins, transaction `000-76d66938`

**Comment by yegor256** [comment]
@k0r all team members should be in that team, everybody who is working with the project now

**Comment by k0r** [comment]
@yegor256 a list would help.

**Comment by k0r** [comment]
@yegor256 please list all team members actively involved, and I'll add them to the team `nerodesk`

**Comment by yegor256** [comment]
@k0r here you go: @darkled @caarlos0 @carlosmiranda @krzyk @dmzaytsev @pinaf @ggajos @longtimeago

**Comment by k0r** [comment]
added @darkled @caarlos0 @carlosmiranda @krzyk @dmzaytsev @pinaf @ggajos @longtimeago to `nerodesk` team.

**Comment by karato** [comment]
@yegor256 Thanks for your contribution, **30 mins** was added to your account, payment ID is `000-18e09e96`, 601 hours and 27 mins spent total. +30 to your rating, your total score is [+7021](http://www.netbout.com/b/35008?open=rating)
