### ISSUE TITLE
user interface cleanup

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#272]
Let's clean up user interface a bit, including: 
- hardcoded the storage amount on the front page
- remove visibility of PayPal balance

**Comment by k0r** [comment]
@yegor256 does this mean implementing total storage or just removing the xsl text?

**Comment by karato** [comment]
@yegor256 there is no milestone yet, so I set it to `0.7`

**Comment by k0r** [comment]
![nd_storage_amt_rnd_error](https://cloud.githubusercontent.com/assets/12001062/7529238/117683e8-f4ea-11e4-96ca-5b9ba72aa724.jpg)

**Comment by karato** [comment]
@yegor256 your task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-78815a79`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.23`

**Comment by yegor256** [comment]
@k0r seems to be working, I'm closing the ticket

**Comment by karato** [comment]
@yegor256 Much appreciated! **1 hour** was added to your account, payment ID `000-69478c7b`, time spent is 2 hours and 5 mins

m=125, that's why a bonus here for fast delivery

+60 to your rating, your total score is [+8874](http://www.netbout.com/b/35008?open=rating)
