### ISSUE TITLE
docs file requires file size

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#274]
online version of the file panel lists all of my docs at `977kb` whereas dev mode lists the correct sizes of uploaded docs files. to replicate, upload files into the online version of the system and check file sizes.

**Comment by k0r** [comment]
@rultor hello

**Comment by k0r** [comment]
@rultor release, tag is `0.3.25`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.25`

**Comment by k0r** [comment]
![nd_storage_amt_rnd_error](https://cloud.githubusercontent.com/assets/12001062/7548163/ca5aff82-f5b3-11e4-8cdc-73731de4c8b5.jpg)

**Comment by k0r** [comment]
my files: all listed as `977kb` online
![nd_file_size_bug](https://cloud.githubusercontent.com/assets/12001062/7548164/cfd33128-f5b3-11e4-8cb7-7f5b0e77ba0a.jpg)

**Comment by k0r** [comment]
pinafs files: various file sizes in dev mode
![nd_file_size_bug2](https://cloud.githubusercontent.com/assets/12001062/7548191/917abf12-f5b4-11e4-99b6-057a56ec10a9.jpg)

**Comment by k0r** [comment]
@yegor256 docs per file size differs online from dev mode. @pinaf helped me find this bug. thanks.

**Comment by pinaf** [comment]
@k0r no problem :)

**Comment by k0r** [comment]
@yegor256 bug confirmed?

**Comment by yegor256** [comment]
@k0r can you please explain in the ticket description what the bug is about and how can I reproduce it

**Comment by k0r** [comment]
@yegor256 updated.

**Comment by yegor256** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@yegor256 tag "bug" added

**Comment by k0r** [comment]
@yegor256 this is important for presentations.

**Comment by k0r** [comment]
@yegor256 this needs to be fixed asap.

**Comment by yegor256** [comment]
@karato pls assign @pinaf to this

**Comment by yegor256** [comment]
@pinaf can you fix this ASAP?

**Comment by k0r** [comment]
@yegor256 lets reassign this task to @dmzaytsev.

**Comment by pinaf** [comment]
@yegor256 @k0r sorry guys I fell ill last Friday and just got back to the computer now

**Comment by k0r** [comment]
@pinaf welcome back ;-]

**Comment by pinaf** [comment]
@k0r Is the online version localted at nerodesk.com? If so, I can't login with github :(

**Comment by dmzaytsev** [comment]
@pinaf FYI #210

**Comment by pinaf** [comment]
@dmzaytsev nice catch :) @k0r so there's a puzzle for it. why don't you let @dmzaytsev take care of it?

**Comment by dmzaytsev** [comment]
@pinaf I can't fix it ASAP, sorry

**Comment by k0r** [comment]
@dmzaytsev at your earliest convenience is ok, doesn't have to be ASAP (in this case).

**Comment by dmzaytsev** [comment]
@k0r @yegor256 @pinaf @karato okay let's assign the puzzle #210 to me if you don't mind

**Comment by yegor256** [comment]
@karato assign @dmzaytsev to this pls

**Comment by karato** [comment]
> @karato pls assign @pinaf to this

@yegor256 OK @pinaf please go ahead, this task is yours

**Comment by karato** [comment]
> @karato assign @dmzaytsev to this pls

@yegor256 of course! @dmzaytsev it's your ticket now, please go ahead

**Comment by k0r** [comment]
@rultor hello

**Comment by k0r** [comment]
@rultor release, tag is `0.3.31`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.31`

**Comment by k0r** [comment]
@yegor256 `java.lang.NullPointerException`

**Comment by k0r** [comment]
@yegor256 this needs to be fixed asap. the site is getting social media traction.

**Comment by dmzaytsev** [comment]
@k0r @yegor256 I wiil fix it. NPE occurs only on online version.

**Comment by k0r** [comment]
@dmzaytsev the site isn't accessible. `error on line 1 at column 1: Document is empty`

**Comment by k0r** [comment]
@dmzaytsev please provide an ETA of when this will be fixed.

**Comment by dmzaytsev** [comment]
@k0r 5 min

**Comment by k0r** [comment]
@rultor release, tag is `0.3.32`

**Comment by dmzaytsev** [comment]
@k0r one  more commit

**Comment by k0r** [comment]
@rultor release, tag is `0.3.32`

**Comment by k0r** [comment]
@dmzaytsev many thanks.

**Comment by k0r** [comment]
@rultor release, tag is `0.3.33`

**Comment by k0r** [comment]
@yegor256 confirm?

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.33`

**Comment by k0r** [comment]
`

**Comment by dmzaytsev** [comment]
@k0r I think we may close this issue. It fixed in #291

**Comment by k0r** [comment]
@yegor256 release tag failed.

**Comment by yegor256** [comment]
@k0r yes, because master is broken :(

**Comment by dmzaytsev** [comment]
@k0r could you please close this issue? It fixed in #291

**Comment by dmzaytsev** [comment]
@karato we need more time here

**Comment by karato** [comment]
> @karato we need more time here

@dmzaytsev yes, take your time, thanks for letting me know

**Comment by k0r** [comment]
@rultor hello

**Comment by k0r** [comment]
@rultor release, tag is `0.3.33`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.33`

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by karato** [comment]
@dmzaytsev Much appreciated! **30 mins** was added to your account, payment ID `58538977`, time spent is 166 hours and 30 mins; added +30 to your rating, now it is equal to [+2057](http://www.netbout.com/b/35166?open=rating)
