### ISSUE TITLE
TkSetVisibilityTest.java:95-99: Make visibility functionality in MkAttributes...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#278]
Puzzle `255-bf924f1e` in `src/test/java/com/nerodesk/takes/doc/TkSetVisibilityTest.java:95-99` has to be resolved: Make visibility functionality in MkAttributes be a function of the underlying file instead of a boolean field. This is necessary in order for different instances of MkDoc which point to the same underlying file to see the same visibility status. Once this is done, un-ignore the test below.... The puzzle was created by Felipe Pina on 11-May-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@yegor256 there is no milestone yet, so I set it to `0.7`

**Comment by karato** [comment]
@pinaf do this task

**Comment by pinaf** [comment]
@karato please assign someone else

**Comment by karato** [comment]
> @karato please assign someone else

@pinaf deducted 30 from your rating :(

**Comment by karato** [comment]
> @karato please assign someone else

@pinaf all right, we'll find someone else for this task

**Comment by karato** [comment]
@carlosmiranda do this task

**Comment by carlosmiranda** [comment]
@karato waiting for #285 here.

**Comment by karato** [comment]
> @karato waiting for #285 here.

@carlosmiranda yes, waiting for #285

**Comment by karato** [comment]
@yegor256 I think we can continue, impediment #285 is closed

**Comment by karato** [comment]
@yegor256 We are done here, thanks all

**Comment by karato** [comment]
@carlosmiranda **30 mins** sent to your balance (ID `58075257`), many thanks! It took 92 hours and 42 mins.. +30 to your rating, your total score is [+4201](http://www.netbout.com/b/35023?open=rating)
