### ISSUE TITLE
bit.ly integration requires cache for latency improvement

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#280]
latency to `beta.nerodesk.com` can be improved by implementing cache for bit.ly integration. normal site load is less than `100ms.` to replicate, connect to the site.

**Comment by k0r** [comment]
@yegor256 bug confirmed?

**Comment by yegor256** [comment]
@karato it's a valid bug

**Comment by yegor256** [comment]
@k0r we don't cache bit.ly responses and on every page load go to their server in order to create a new short URL. that's definitely redundant and must be fixed

**Comment by k0r** [comment]
@yegor256 thanks.

**Comment by karato** [comment]
> @karato it's a valid bug

@yegor256 tag "bug" added

**Comment by karato** [comment]
@k0r attached this issue to milestone "0.7" (let me know if this is wrong)

**Comment by k0r** [comment]
@yegor256 please assign @dmzaytsev to this task.

**Comment by yegor256** [comment]
@karato assign @dmzaytsev to this task pls

**Comment by dmzaytsev** [comment]
@karato please see PR #290

**Comment by k0r** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
> @karato assign @dmzaytsev to this task pls

@yegor256 done. @dmzaytsev the task is yours, please go ahead

**Comment by karato** [comment]
> @karato please see PR #290 

@dmzaytsev I will take a look, thanks

**Comment by k0r** [comment]
@rultor hello

**Comment by k0r** [comment]
@rultor release, tag is `0.3.30`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.30`

**Comment by dmzaytsev** [comment]
@k0r We may close close this issue now. Implemented in #290

**Comment by k0r** [comment]
@dmzaytsev bit.ly links are all the same.

**Comment by k0r** [comment]
@dmzaytsev bit.ly links were functioning until today.

**Comment by dmzaytsev** [comment]
@yegor256 should we open a new issue in this case?

**Comment by k0r** [comment]
@dmzaytsev #301

**Comment by k0r** [comment]
@dmzaytsev this ticket might also be broken as well. latency has increased.

**Comment by dmzaytsev** [comment]
@k0r should be resolved in #303

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by dmzaytsev** [comment]
@karato we're waiting for #299 here

**Comment by karato** [comment]
> @karato we're waiting for #299 here

@dmzaytsev yep, got it, let's wait for #299 being solved

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by karato** [comment]
@dmzaytsev **30 mins** was added to your account, many thanks for your contribution! The task took 58538985.... added +30 to your rating, now it is equal to [+2087](http://www.netbout.com/b/35166?open=rating)
