### ISSUE TITLE
null file field causes aws to return 404

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#283]
`amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found [...])`. to replicate, click upload without a file selected.

**Comment by yegor256** [comment]
@k0r very close to #232 I would say we should fix that first and then this problem will just go away, I believe

**Comment by karato** [comment]
@yegor256 don't close it, ask @k0r to do do it, since he created it, thanks!

**Comment by karato** [comment]
@k0r since there is no milestone yet I set it to "0.7"

**Comment by yegor256** [comment]
@k0r is it still a problem? please check again

**Comment by k0r** [comment]
@yegor256 thanks.
