### ISSUE TITLE
implement disqus for beta feedback

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#287]

**Comment by k0r** [comment]
@rultor hello

**Comment by k0r** [comment]
@rultor release, tag is `0.3.29`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.29`

**Comment by yegor256** [comment]
@k0r keep in mind that it's a bad practice to commit directly to master branch, see http://www.yegor256.com/2014/07/21/read-only-master-branch.html

**Comment by yegor256** [comment]
@k0r it's a bug in Github plugin, recently reported: https://github.com/github/maven-plugins/issues/88

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.29`

**Comment by k0r** [comment]
@yegor256 thanks.
