### ISSUE TITLE
travis ci build status is broken

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#299]

**Comment by k0r** [comment]
@dmzaytsev new PRs are failing because the `master` branch is broken.

**Comment by k0r** [comment]
@dmzaytsev can you fix this?

**Comment by k0r** [comment]
can anyone fix this?

**Comment by k0r** [comment]
@rultor can't deploy, merge, or release until the `master` branch is fixed.

**Comment by yegor256** [comment]
@karato assign @dmzaytsev to this pls

**Comment by karato** [comment]
@k0r we will find someone to do this task, soon

**Comment by karato** [comment]
@k0r there is no milestone yet, so I set it to `0.4`

**Comment by karato** [comment]
> @karato assign @dmzaytsev to this pls

@yegor256 done. @dmzaytsev the task is yours, please go ahead

**Comment by dmzaytsev** [comment]
@karato please see PR #304

**Comment by karato** [comment]
> @karato please see PR #304 

@dmzaytsev thanks, I'll take a look

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by karato** [comment]
@dmzaytsev Thanks for your contribution, **38 mins** was added to your account, payment ID is `58539008`, 65 hours and 28 mins spent total; the bonus for fast delivery (m=3928); +38 to your rating, your total score is [+2125](http://www.netbout.com/b/35166?open=rating)
