### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#3]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by karato** [comment]
@ggajos this is your task

**Comment by ggajos** [comment]
@karato #4 merged, you can close if that's all here

**Comment by yegor256** [comment]
@rultor deploy

**Comment by karato** [comment]
The task is done, thanks all, I am closing it

**Comment by karato** [comment]
@ggajos Much appreciated! **30 mins** was added to your account, payment ID `AP-9K292204M3823433Y`

+30 added to your rating, at the moment it is: [+1584](http://www.netbout.com/b/35094?open=rating)
