### ISSUE TITLE
Storage.java:45-47: Implement delete operation to remove...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#30]
Puzzle `13-f1fbb1e7` in `src/main/java/com/nerodesk/Storage.java:45-47` has to be resolved: Implement delete operation to remove file from the storage. In MkStorage.delete() implementation file should be removed from local file system. Don't forget about unit tests.... The puzzle was created by longtimeago on 23-Feb-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@pinaf do this task

**Comment by pinaf** [comment]
@karato merged. please close if alright.

**Comment by karato** [comment]
The issue is closed

**Comment by karato** [comment]
@pinaf done, I added **30 mins** in payment `AP-57T38276LY1418907`. added +30 to your rating, now it is equal to [+2831](http://www.netbout.com/b/35128?open=rating)
