### ISSUE TITLE
bit.ly links are broken

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#301]
all of the bit.ly generated links are the same.

**Comment by dmzaytsev** [comment]
@yegor256 @karato please assign it to me

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by dmzaytsev** [comment]
@yegor256 is this issue classified as bug?

**Comment by k0r** [comment]
@rultor release, tag is `0.3.34`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.34`

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by dmzaytsev** [comment]
@yegor256 should I expect a payment for this ticket?
I understand that it is my fault the ticket didn't classify as bug and I didn't assign to the ticket. But it was an urgent issue and I see that the changes were accepted

**Comment by yegor256** [comment]
@dmzaytsev indeed, it's your fault, the task was never assigned to you. don't do it like this, it's against of the entire management model.

**Comment by k0r** [comment]
@yegor256 an exception should be provided for @dmzaytsev in this case.

**Comment by yegor256** [comment]
@k0r OK, I reopened it and it will be assigned to @dmzaytsev soon. Then, he will ask you to close it. Once you close, the task will be paid

**Comment by k0r** [comment]
@yegor256 thanks.

**Comment by karato** [comment]
@k0r since the ticket has no milestone I set it to 0.4

**Comment by karato** [comment]
@dmzaytsev do this task, 30 mins is budget

**Comment by yegor256** [comment]
@k0r you can close this ticket

**Comment by k0r** [comment]
@yegor256 thanks.

**Comment by dmzaytsev** [comment]
@k0r @yegor256 thank you very much!

**Comment by karato** [comment]
@dmzaytsev I added **1 hour** to your account, many thanks for working with the project! The completion time here was 58609681.... there is a bonus for fast delivery (m=268)... +60 added to your rating, current score is: [+2215](http://www.netbout.com/b/35166?open=rating)
