### ISSUE TITLE
docs panel update

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#305]
update the docs panel to look like the following image.
- comment out new directory feature (implementation postponed indefinitely)
- comment out email sharing feature (email takes `link` sharing postponed indefinitely)
- move bit.ly `link` to options column underneath `delete`
- rename `link` to `share`
- file permission checkbox (if `public` and `private` file visibility is near completion or completed)

![docs_update](https://cloud.githubusercontent.com/assets/12001062/7925392/bf6e5128-0878-11e5-839c-55a55b9af3fa.jpg)

**Comment by k0r** [comment]
@yegor256 updated.

**Comment by k0r** [comment]
@yegor256 how close is `public` and `private file visibility to implementation?

**Comment by k0r** [comment]
@yegor256 how close is `public` and `private` file visibility to implementation?

**Comment by k0r** [comment]
@yegor256 this is a landmark ticket, let's make an effort to complete it. once it's finished, `nerodesk` will have pivoted towards project completion.

**Comment by k0r** [comment]
@yegor256 updated.

**Comment by k0r** [comment]
@yegor256 developers for this ticket required.

**Comment by yegor256** [comment]
@karato assign @dmzaytsev pls

**Comment by karato** [comment]
@k0r this task will get someone's attention soon

**Comment by karato** [comment]
@k0r milestone set to `0.4` (correct me if I am wrong)

**Comment by karato** [comment]
@maurezen this is your task

**Comment by karato** [comment]
> @karato assign @dmzaytsev pls

@yegor256 of course! @dmzaytsev it's your ticket now, please go ahead

**Comment by dmzaytsev** [comment]
@karato please see PR #311

**Comment by karato** [comment]
> @karato please see PR #311 

@dmzaytsev thanks, will take a look

**Comment by k0r** [comment]
@rultor hello

**Comment by k0r** [comment]
@rultor release, tag is `0.3.36`

**Comment by dmzaytsev** [comment]
@k0r PR #311 fixed the issue please close the ticket

**Comment by k0r** [comment]
@yegor256 confirm.

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.36`

**Comment by k0r** [comment]
@dmzaytsev accessing a `public` file when logged out causes `org.takes.facets.forward.RsForward: [303] [303] / WARNING/access denied`

**Comment by k0r** [comment]
@yegor256 [this](https://github.com/Nerodesk/nerodesk/issues/305#issuecomment-107695773).

**Comment by k0r** [comment]
@dmzaytsev checkbox doesn't retain checked status. @yegor256 does this require id persistence?

**Comment by k0r** [comment]
@yegor256 looking at [this](http://www.yegor256.com/2015/05/21/avoid-software-outsourcing-disaster.html), there are several inconsistencies with this ticket.

**Comment by yegor256** [comment]
@k0r what inconsistencies are you talking about? Please explain

**Comment by yegor256** [comment]
@k0r please, keep in mind that we resolve one problem per ticket

**Comment by k0r** [comment]
> be open about your concerns.

no feedback from [this](https://github.com/Nerodesk/nerodesk/issues/305#issuecomment-107695773), which could've improved quality of this feature.

**Comment by dmzaytsev** [comment]
@k0r I did all as you requested in the ticket description. It works well on the local instance. I can't test real application before it be released. There is a bug with the visibility persistence on the real instance. I'll report about it. So no reason to not close this particular ticket.
@yegor256 what do you think?

**Comment by yegor256** [comment]
@dmzaytsev @k0r yes, I agree, the problem explained above (in the description of the ticket) is solved and the ticket should be closed. All other problems we'll resolve in new tickets.

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by karato** [comment]
@dmzaytsev **30 mins** was added to your account, many thanks for your contribution (payment 58678902)! The task took 72 hours and 27 mins.... +30 added to your rating, at the moment it is: [+2320](http://www.netbout.com/b/35166?open=rating)
