### ISSUE TITLE
downloaded file missing file name and extension

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#306]
a downloaded file from the `docs` panel is missing the appropriate file name and extension. the file downloaded is simply called `read` without the appropriate name and extension. the file name should be identical to the file name and extension that is listed in the `docs` panel. 

to replicate, upload a file then download.

**Comment by k0r** [comment]
@yegor256 this needs to be fixed asap.

**Comment by k0r** [comment]
@yegor256 this needs to be fixed asap.

**Comment by dmzaytsev** [comment]
@karato please see PR #307

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by karato** [comment]
@k0r milestone set to `0.4` (correct me if I am wrong)

**Comment by karato** [comment]
@dmzaytsev do this task, 30 mins is budget

**Comment by karato** [comment]
> @karato please see PR #307

@dmzaytsev thank you, I will check it

**Comment by k0r** [comment]
@rultor hello

**Comment by k0r** [comment]
@rultor release, tag is `0.3.35`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.35`

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by dmzaytsev** [comment]
@k0r  PR #307 fixed this issue please close if alright

**Comment by karato** [comment]
@dmzaytsev Thanks for your contribution, **45 mins** was added to your account, payment ID is `58636945`, 31 hours and 40 mins spent total

there is a bonus for fast delivery (m=1900)

+45 to your rating, your total score is [+2305](http://www.netbout.com/b/35166?open=rating)
