### ISSUE TITLE
login panel requires update

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#308]
update the `login` panel to look like the following image.
- implement logging in with `twitter`
- implement logging in with `github`

![login_page_update](https://cloud.githubusercontent.com/assets/12001062/7947391/a4b41340-0931-11e5-9e7e-be14b0373048.jpg)

**Comment by yegor256** [comment]
@k0r would be easier to replace twitter with Google+. Easier for me, implementation wise. What do you think?

**Comment by k0r** [comment]
@yegor256 twitter is preferred, that's where `nerodesk` has a growing social media presence.

**Comment by yegor256** [comment]
@k0r ok, twitter it is

**Comment by k0r** [comment]
@yegor256 thanks.
