### ISSUE TITLE
Storage.java:42-44: Implement put operation to add...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#31]
Puzzle `13-97594e76` in `src/main/java/com/nerodesk/Storage.java:42-44` has to be resolved: Implement put operation to add file to the storage. In MkStorage.put() implementation file should be stored on local file system. Don't forget about unit tests.... The puzzle was created by longtimeago on 23-Feb-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@ggajos do this task

**Comment by ggajos** [comment]
@karato you can see pull request above that is fixing this issue, if that's all here please close.

**Comment by ggajos** [comment]
@karato #33 is fixing this issue, please close if that's all here, thank you

**Comment by ggajos** [comment]
@karato please close if that's all here, thanks

**Comment by karato** [comment]
> @karato please close if that's all here, thanks

@ggajos I will close it when the puzzle disappears from the source code, and keep in mind that it may take up to a day to update project stats after a successful deployment

**Comment by karato** [comment]
@ggajos thank you, added **30 mins** to your acc, payment num is `AP-4KJ15566JH246062M`

added +30 to your rating, now it is equal to [+2415](http://www.netbout.com/b/35094?open=rating)

**Comment by karato** [comment]
Closed, done, thanks all

**Comment by ggajos** [comment]
@karato so you're waiting for deployment of feature, not merge?
