### ISSUE TITLE
file integrity loss after upload

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#310]
uploaded files loose integrity and become corrupted. to replicate, upload a file then download.

so far, here are the file types that are affected:

**.mp4** [[before](http://www.nerodesk.com/ticket310/test_movie_before.mp4) | [after](http://www.nerodesk.com/ticket310/test_movie_after.mp4)]
`file size: 9mb`
`after 15 seconds, the video isn't consistent with original.`

**.jpg** [[before](http://www.nerodesk.com/ticket310/test_image_before.jpg) | [after](http://www.nerodesk.com/ticket310/test_image_after.jpg)]
`file size: 24mb`
`jpeg image isn't consistent with original.`

**.bmp** [[before](http://www.nerodesk.com/ticket310/test_image_before.bmp) | [after](http://www.nerodesk.com/ticket310/test_image_after.bmp)]
`file size: 10mb`
`bitmap image isn't consistent with original.`

**.flac** [[before](http://www.nerodesk.com/ticket310/test_music_before.flac) | [after](http://www.nerodesk.com/ticket310/test_music_after.flac)]
`file size: 14mb`
`skipping throughout the track.`

**.psd**
`file size: 23mb`
`photoshop "could not complete your request" error.`

**.pdf**
`file size: 5mb`
`missing pages.`

**Comment by k0r** [comment]
@yegor256 ...

**Comment by k0r** [comment]
@yegor256 any ideas?

**Comment by k0r** [comment]
@dmzaytsev suggestions?

**Comment by dmzaytsev** [comment]
@k0r it needs to be investigated... Is it reproduceble on the local instance?

**Comment by k0r** [comment]
@dmzaytsev let me know if it is.

**Comment by k0r** [comment]
@yegor256 this ticket should be prioritized and fixed. can't have files getting corrupted.

**Comment by k0r** [comment]
@yegor256 system can't be used until this is fixed. this ticket should be prioritized.

**Comment by k0r** [comment]
@yegor256 thanks.

**Comment by karato** [comment]
@k0r I set milestone here to `0.4`, let me know if it is wrong

**Comment by karato** [comment]
@dmzaytsev do this task, 30 mins is budget

**Comment by k0r** [comment]
@yegor256 updated.

**Comment by k0r** [comment]
@yegor256 updated.

**Comment by yegor256** [comment]
@dmzaytsev I suspect it's an issue with UTF-8 encoding...

**Comment by dmzaytsev** [comment]
@yegor256 I'm not sure

**Comment by k0r** [comment]
@yegor256 looking at [this](http://www.yegor256.com/2015/05/21/avoid-software-outsourcing-disaster.html), there are inconsistencies with this ticket.

**Comment by k0r** [comment]
> everything in this [section](http://www.yegor256.com/2015/05/21/avoid-software-outsourcing-disaster.html#the-product-is-so-clumsy)
> this is how you stabilize the project and minimize risks.

file upload is the core of this application, and currently lacks business sustainable quality.

**Comment by dmzaytsev** [comment]
@karato we are waiting yegor256/takes#331

**Comment by k0r** [comment]
@dmzaytsev not sure about the solution you've suggested. to fix this ticket, I'd prefer if the solution was thoroughly researched. this is the most important feature of the application.

**Comment by dmzaytsev** [comment]
@k0r sure, I taken into account

**Comment by k0r** [comment]
@yegor256 any progress with this ticket?

**Comment by yegor256** [comment]
@k0r let's wait for the fix in Takes, hopefully it will solve the problem here too

**Comment by k0r** [comment]
@yegor256 thanks.

**Comment by yegor256** [comment]
@dmzaytsev takes 0.20.1 was released a few minutes ago, I think you can go ahead and try to solve the problem here

**Comment by dmzaytsev** [comment]
@karato please see PR #316

**Comment by k0r** [comment]
@rultor hello

**Comment by k0r** [comment]
@rultor release, tag is `0.3.37`

**Comment by karato** [comment]
> @karato please see PR #316 

@dmzaytsev thanks, will take a look

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.37`

**Comment by k0r** [comment]
@yegor256 @dmzaytsev thanks.

**Comment by k0r** [comment]
@yegor256 @dmzaytsev seems to have been fixed.

**Comment by dmzaytsev** [comment]
@k0r PR #316 fixed this issue, please close the ticket, thank you

**Comment by dmzaytsev** [comment]
@karato I need more time here

**Comment by karato** [comment]
> @karato I need more time here

@dmzaytsev agreed, take your time

**Comment by karato** [comment]
@dmzaytsev Thanks a lot, I just topped your account for **30 mins**, transaction ID `59071226`, total time was 166 hours... +30 to your rating, your total score is [+2645](http://www.netbout.com/b/35166?open=rating)
