### ISSUE TITLE
Rultor and Travis inconsistence

### ISSUE THREAD

**Issue by asaen** [Nerodesk/nerodesk#34]
For the moment `.rultor.yml` makes `mvn clean install -Pqulice,cobertura` while `.travis.yml` executes only `mvn clean install -Pqulice`. Let's include cobertura checks into travis builds as well.

**Comment by ggajos** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@ggajos OK, I labeled it as `bug`

**Comment by karato** [comment]
I will ask someone to take care of this task soon

**Comment by karato** [comment]
@ggajos this is your task

**Comment by karato** [comment]
@darkled thanks for the report, I topped your acc for 15 mins, payment ID `52781668`

**Comment by ggajos** [comment]
see #38

**Comment by ggajos** [comment]
@darkled please close if that's all here, thanks

**Comment by asaen** [comment]
@ggajos thanks

**Comment by karato** [comment]
@ggajos Much appreciated! **30 mins** was added to your account, payment ID `AP-81M035239U686414G`

+30 to your rating, your total score is [+2596](http://www.netbout.com/b/35094?open=rating)
