### ISSUE TITLE
Section "How to contribute" is out of date

### ISSUE THREAD

**Issue by asaen** [Nerodesk/nerodesk#42]
The section "How to contribute" of `README.md` should tell us to invoke `mvn clean install -Pqulice,cobertura` since cobertura checks are added to travis build.

**Comment by ggajos** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@ggajos OK, I labeled it as `bug`

**Comment by karato** [comment]
@ggajos do this task

**Comment by karato** [comment]
@darkled many thanks for the report, I topped your account for 15 mins, transaction 52908201

**Comment by ggajos** [comment]
@darkled please close if that's all here, thanks

**Comment by asaen** [comment]
@ggajos thanks, closing...

**Comment by karato** [comment]
@ggajos thanks, I just added **30 mins** to your account, payment `AP-24814386FY1656325`... +30 added to your rating, at the moment it is: [+2904](http://www.netbout.com/b/35094?open=rating)
