### ISSUE TITLE
Option UseSplitVerifier; support was removed in 8.0

### ISSUE THREAD

**Issue by pinaf** [Nerodesk/nerodesk#43]
Seems like this option is configured in pom.xml for maven-surefire

> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0

this happens when building with `mvn clean install -Pqulice,cobertura`. Using java8 oracle:

> java version "1.8.0_31"
> Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by asaen** [comment]
@pinaf it is fixed within #18 and will be available after merge of PR #36

**Comment by pinaf** [comment]
@darkled thank you.
