### ISSUE TITLE
rultor should work with java 8

### ISSUE THREAD

**Issue by asaen** [Nerodesk/nerodesk#46]
For the moment we cannot merge changes to use java 8 since rultor is working with `JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64`. To continue we need to update java. Full build log is [here](http://www.rultor.com/t/2347-77322916).

**UPD 2**
We need to update `.rultor.yml` appending the following snippet

```
docker:
  image: "mostalive/ubuntu-14.04-oracle-jdk8"
```

**Comment by ggajos** [comment]
@yegor256 rultor doesn't support java 8?

**Comment by longtimeago** [comment]
@ggajos looks like that

**Comment by ggajos** [comment]
@pinaf @yegor256 @darkled think there is no point in waiting for rultor to be compatibile. Let's downgrade minimum version to 7.

**Comment by yegor256** [comment]
@ggajos rultor supports whatever platform you need. here is how you configure it in `.rultor.yml`:

```
docker:
  as_root: true
  image: hanswesterbeek/google-debian-oracle-jdk:8
```

Basically, we just need to use another Docker container, with Java 8 pre-installed. This container is Debian. If you can find a better one, which is Ubuntu, will be even better.

**Comment by yegor256** [comment]
@ggajos search them here: https://registry.hub.docker.com/search?q=library

**Comment by ggajos** [comment]
@yegor256 thanks for feedback, couldn't find clear answer for that; I think we can try that and switch docker image to use jdk8 while keeping compatibility with Java7 for now; don't want to create additional blockers for tickets.

**Comment by ggajos** [comment]
@karato it's valid bug

**Comment by ggajos** [comment]
let's change rultor yml as @yegor256 suggested

**Comment by ggajos** [comment]
@darkled please update description a bit so assigned person will know how to proceed, thanks

**Comment by yegor256** [comment]
@ggajos I would actually suggest to find a better Docker container with Java8, which is not Debian. Ubuntu sounds like a better option for all other tools we're using... but this container is the only option, you can use it

**Comment by ggajos** [comment]
@ye

**Comment by karato** [comment]
> @karato it's valid bug

@ggajos got it, tag `bug` is here

**Comment by karato** [comment]
@ggajos do this task

**Comment by karato** [comment]
@darkled thanks for the ticket, your account was topped for 15 mins, payment 52909214

**Comment by ggajos** [comment]
we're waiting for #18 here

**Comment by pinaf** [comment]
@ggajos have you guys tried https://registry.hub.docker.com/u/sdorra/oracle-java-8/ ?

**Comment by pinaf** [comment]
@ggajos @darkled  or this  https://registry.hub.docker.com/u/carrotgarden/java-8/dockerfile/

**Comment by pinaf** [comment]
@yegor256 is `as_root: true` necessary?

**Comment by asaen** [comment]
@pinaf in PR #47 we're using `mostalive/ubuntu-14.04-oracle-jdk8`. Do you think it won't pass our requirments?

**Comment by pinaf** [comment]
@darkled it should - I hadn't seen that PR :)

**Comment by pinaf** [comment]
@darkled I'm going to ask you to do the same on another project, alright?

**Comment by asaen** [comment]
@pinaf yes, sure

**Comment by yegor256** [comment]
@pinaf `as_root: true` is not really necessary, don't use it

**Comment by asaen** [comment]
@ggajos Could you please update `.rultor.yml` in the way of updated issue description? Since rultor always gets `.rultor.yml` from the master branch we are not able to finish #18 without getting this issue done.

**Comment by ggajos** [comment]
@darkled think it's part of #47 already

**Comment by asaen** [comment]
@ggajos yes and no :) We need modified `.rultor.yml` in the master branch to be able to merge #47

**Comment by ggajos** [comment]
@karato please assign someone else

**Comment by ggajos** [comment]
@darkled sorry for troubles, have huge time issues this week :/

**Comment by karato** [comment]
> @karato please assign someone else

@ggajos OK, I will try to assign someone else

**Comment by karato** [comment]
@longtimeago do this task

**Comment by longtimeago** [comment]
PR https://github.com/teamed/nerodesk/pull/59 is available. Hope guys @ggajos @darkled I understood you correctly.

**Comment by longtimeago** [comment]
@karato we need more time here

**Comment by karato** [comment]
> @karato we need more time here

@longtimeago sure, thanks for telling me, take your time

**Comment by longtimeago** [comment]
@darkled I think we can close the issue. Build is OK with java8

**Comment by longtimeago** [comment]
@darkled can we close it?

**Comment by asaen** [comment]
@longtimeago I am not sure actually, because `.rultor.yml` doesn't have set docker image...
@yegor256 I see you removed docker image with the latest commit, won't we use java 8 anymore with rultor?

**Comment by yegor256** [comment]
@darkled there is no point in Java8 in this project. Java7 works just fine.

**Comment by asaen** [comment]
@yegor256 @longtimeago ok, thank you, closing the issue

**Comment by karato** [comment]
@longtimeago I added **30 mins** to your account, many thanks for working with the project!. +30 to your rating, your total score is [+3053](http://www.netbout.com/b/35024?open=rating)
