### ISSUE TITLE
FtCLI and upgrade to takes 0.8.4

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#61]
Let's use `FtCLI` in `Launch`, since it allows command line arguments parsing. Also, let's upgrade takes to version 0.8.4 (the latest one), which will give us that class.

**Comment by yegor256** [comment]
also, we'll have to modify `Procfile` and replace `${PORT}` with `--port=${PORT}`

**Comment by karato** [comment]
@yegor256 do this task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 many thanks for the bug report, I added 15 mins to your acc, transaction `000-74ea341f`

**Comment by yegor256** [comment]
done

**Comment by karato** [comment]
@yegor256 Much obliged! I have added **30 mins** to your account in payment "000-1668fc1d". +30 added to your rating, at the moment it is: [+8373](http://www.netbout.com/b/35008?open=rating)
