### ISSUE TITLE
RqRegex.Fake from takes 0.8.5

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#62]
Let's use `RqRegex.Fake` from takes 0.8.5 in `TkGetFileTest`. The use of this class will make the test way shorter and easier to read.

Also, it's a bad idea to have that public static property `PATH` in `TkGetFile`. There is not connection between a regular expression used in `Launch`. We can use two absolutely different regular expressions - one in `Launch` and another one in tests.

In general, `public static` is a terrible violation of OOP principles, try to avoid that.

**Comment by karato** [comment]
@yegor256 right, I added the `bug` tag

**Comment by karato** [comment]
@longtimeago this is your task

**Comment by karato** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-ceed7be5`

**Comment by longtimeago** [comment]
PR https://github.com/teamed/nerodesk/pull/71 is available for review

**Comment by yegor256** [comment]
@longtimeago please wait for https://github.com/teamed/nerodesk/pull/77

**Comment by longtimeago** [comment]
@karato waiting for #77

**Comment by karato** [comment]
> @karato waiting for #77

@longtimeago right, let's wait for #77

**Comment by karato** [comment]
we were waiting for #77 - it is closed already

**Comment by longtimeago** [comment]
@yegor256 there's nothing to do here after your refactoring :(

**Comment by yegor256** [comment]
yeah, the problem is gone

**Comment by karato** [comment]
@longtimeago **30 mins** was added to your account, many thanks for your contribution!... +30 added to your rating, current score is: [+3128](http://www.netbout.com/b/35024?open=rating)
