### ISSUE TITLE
Storage design is too simple

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#63]
At the moment we have this `Storage` interface, which, I believe, doesn't express the correct design. I would suggest these interfaces to the object model of the app:

``` java
interface User {
  Docs docs();
}
interface Docs {
  List<Doc> find(String name); // could return empty list if not found
  List<Doc> list(String prefix); // finds all docs by prefix, e.g. "/my/pictures"
}
interface Doc {
  String name();
  void load(OutputStream output);
  void save(InputStream input);
  void delete();
}
```

I would suggest to place them into `com.nerodesk.om` package. Then, create a package `com.nerodesk.om.mock` for their mock versions. Then, create `com.nerodesk.aws` for classes that implement this object model and communicate with AWS.

**Comment by ghost** [comment]
strongly suggest @yegor256 takes over development of this.

**Comment by karato** [comment]
@yegor256 do this task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-4f9a7ac5

**Comment by yegor256** [comment]
fixed

**Comment by yegor256** [comment]
@karato I have spent 3 hours for this:
- redesign of the architect
- implementation of read/write operations
- implementation of mock version of `Base`
- facebook authentication

**Comment by karato** [comment]
> @karato I have spent 3 hours for this:
> - redesign of the architect
> - implementation of read/write operations
> - implementation of mock version of `Base`
> - facebook authentication

@yegor256 3 hours added to your account, transaction `000-f7f691ea`

**Comment by karato** [comment]
2 puzzles were created here: `63-f209efe0`, `63-5fc80ca1`

**Comment by karato** [comment]
@yegor256 Much obliged! I have added **30 mins** to your account in payment "000-4828f081"... +30 added to your rating, at the moment it is: [+8343](http://www.netbout.com/b/35008?open=rating)

**Comment by karato** [comment]
@yegor256 last 2 puzzles `97-5fc80ca1`/#170, `97-a27c5d4c`/#168 originated from here were solved
