### ISSUE TITLE
Launch.java:58-61: Implement DELETE operation to remove...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#65]
Puzzle `14-da645c40` in `src/main/java/com/nerodesk/Launch.java:58-61` has to be resolved: Implement DELETE operation to remove file from the store by file specific path. This might require updates in Takes framework. Don't forget about unit tests.... The puzzle was created by longtimeago on 7-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@carlosmiranda this is your task

**Comment by carlosmiranda** [comment]
@karato Waiting for #77 here.

**Comment by karato** [comment]
> @karato Waiting for #77 here.

@carlosmiranda yes, waiting for #77

**Comment by karato** [comment]
FYI, issue #77 is already closed, and we were waiting for it..

**Comment by karato** [comment]
Thanks all, I am closing

**Comment by karato** [comment]
@carlosmiranda **30 mins** sent to your balance (ID `53785131`), many thanks!. +30 added to your rating, current score is: [+3947](http://www.netbout.com/b/35023?open=rating)
