### ISSUE TITLE
Launch.java:55-57: Implement PUT operation to upload...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#66]
Puzzle `14-9e19a32c` in `src/main/java/com/nerodesk/Launch.java:55-57` has to be resolved: Implement PUT operation to upload file to the store under specific path. This might require updates in Takes framework. Don't forget about unit tests.... The puzzle was created by longtimeago on 7-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@pinaf do this task

**Comment by pinaf** [comment]
@karato please see PR #74

**Comment by yegor256** [comment]
@pinaf please wait for https://github.com/teamed/nerodesk/pull/77

**Comment by pinaf** [comment]
@karato we're waiting for #77 here

**Comment by karato** [comment]
> @karato we're waiting for #77 here

@pinaf sure, let's wait for #77

**Comment by karato** [comment]
#77 is closed, it was an impediment

**Comment by pinaf** [comment]
@karato done.

**Comment by karato** [comment]
Done, thanks all, closing..

**Comment by karato** [comment]
@pinaf Thanks a lot, I just topped your account for **30 mins**, transaction ID `AP-8GS71951E8212650X`; +30 added to your rating, at the moment it is: [+4925](http://www.netbout.com/b/35128?open=rating)
