### ISSUE TITLE
LaunchTest.java:59-60: Application should be able to...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#67]
Puzzle `14-8cd54fa2` in `src/test/java/com/nerodesk/LaunchTest.java:59-60` has to be resolved: Application should be able to get binary file properly. Add a test to check it works and fix if doesn't.... The puzzle was created by longtimeago on 7-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@carlosmiranda this is your task

**Comment by yegor256** [comment]
@carlosmiranda please wait for https://github.com/teamed/nerodesk/pull/77

**Comment by carlosmiranda** [comment]
@karato We're waiting for #77.

**Comment by karato** [comment]
> @karato We're waiting for #77.

@carlosmiranda sure, let's wait for #77

**Comment by karato** [comment]
impediment in issue #77 is closed, we can probably try to continue here

**Comment by carlosmiranda** [comment]
@yegor256 Looks like this puzzle was moved from `LaunchTest` to `AppTest` in #77. Should I continue working on it assuming that it's in `AppTest`?

**Comment by yegor256** [comment]
@carlosmiranda yes, sure

**Comment by carlosmiranda** [comment]
@karato Waiting for #124 (pull request).

**Comment by karato** [comment]
> @karato Waiting for #124 (pull request).

@carlosmiranda yes, right, let's wait for #124

**Comment by karato** [comment]
#124 is closed, it was an impediment

**Comment by karato** [comment]
Thanks, closing it now.

**Comment by karato** [comment]
@carlosmiranda Much obliged! I have added **15 mins** to your account in payment "54232281", 8 hours and 31 mins spent... +15 added to your rating, at the moment it is: [+4327](http://www.netbout.com/b/35023?open=rating)
