### ISSUE TITLE
Launch.java:68-70: Add new section to the...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#69]
Puzzle `14-78da13fc` in `src/main/java/com/nerodesk/Launch.java:68-70` has to be resolved: Add new section to the README described REST API for the file operations available. GET, PUT and DELETE operations should be described.... The puzzle was created by longtimeago on 7-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@pinaf this is your task

**Comment by pinaf** [comment]
@karato please see PR #75

**Comment by yegor256** [comment]
@pinaf please wait for https://github.com/teamed/nerodesk/pull/77

**Comment by pinaf** [comment]
@yegor256 you sure #77 affects this issue?

**Comment by pinaf** [comment]
@karato done.

**Comment by ghost** [comment]
@karato updated the logo.

**Comment by karato** [comment]
Thanks, closed

**Comment by karato** [comment]
@pinaf Thanks for your contribution, **15 mins** was added to your account, payment ID is `AP-6AD22508TG3305408`. +15 added to your rating, current score is: [+4940](http://www.netbout.com/b/35128?open=rating)
