### ISSUE TITLE
Launch.java:52-54: Bind getFile operation to the...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#72]
Puzzle `14-462b19d5` in `src/main/java/com/nerodesk/Launch.java:52-54` has to be resolved: Bind getFile operation to the GET method only. This might require updates in Takes framework. Don't forget about unit tests.... The puzzle was created by longtimeago on 7-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@carlosmiranda this is your task

**Comment by yegor256** [comment]
@carlosmiranda please wait for https://github.com/teamed/nerodesk/pull/77

**Comment by carlosmiranda** [comment]
@karato We're waiting for #77.

**Comment by karato** [comment]
> @karato We're waiting for #77.

@carlosmiranda right, let's wait for #77

**Comment by karato** [comment]
I think we can continue, impediment #77 is closed

**Comment by karato** [comment]
Done, thanks all, closing..

**Comment by karato** [comment]
@carlosmiranda I added **30 mins** to your account, many thanks for working with the project!; +30 added to your rating, at the moment it is: [+3999](http://www.netbout.com/b/35023?open=rating)
