### ISSUE TITLE
Launch.java:65-67: Update FkRegex patterns for all...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#73]
Puzzle `14-186752b9` in `src/main/java/com/nerodesk/Launch.java:65-67` has to be resolved: Update FkRegex patterns for all file operations (get, put, delete) to manage filename with path. Now it works with pure file name only. Don't forget about unit tests.... The puzzle was created by longtimeago on 7-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@longtimeago do this task

**Comment by yegor256** [comment]
@longtimeago please wait for https://github.com/teamed/nerodesk/pull/77

**Comment by longtimeago** [comment]
@karato waiting for #77

**Comment by karato** [comment]
> @karato waiting for #77

@longtimeago yes, right, let's wait for #77

**Comment by karato** [comment]
impediment in issue #77 is closed, we can probably try to continue here

**Comment by longtimeago** [comment]
@yegor256 I think this task is not needed anymore. New design handles file names with path perfectly.

**Comment by yegor256** [comment]
@longtimeago yeah, this puzzle is gone, don't touch this task any more

**Comment by karato** [comment]
Closed, thanks all

**Comment by karato** [comment]
@longtimeago Thanks a lot, I just topped your account for **30 mins**, transaction ID `53800501`; added +30 to your rating, now it is equal to [+3285](http://www.netbout.com/b/35024?open=rating)
