### ISSUE TITLE
upload doesn't work due to bug in takes

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#84]
Takes 0.9.2 has a critical bug, fixed in https://github.com/yegor256/takes/issues/62

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.5`

**Comment by karato** [comment]
@yegor256 do this task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-a6834209`

**Comment by ghost** [comment]
@yegor256 just received an Heroku Application Error upon file upload completion: An error occurred in the application and your page could not be served. Please try again in a few moments.

**Comment by yegor256** [comment]
@k0r how big is the file you're uploading? what is the name of file you're using? I mean, how can I reproduce the error?

**Comment by ghost** [comment]
@yegor256 500mb txt file created with `fsutil` then uploaded.

**Comment by yegor256** [comment]
@k0r that's a separate issue. Let's create a new ticket about it. It happens because the server is trying to put the entire file in memory first. But they maximum memory available is 128Mb. Please create a new ticket for this.

**Comment by karato** [comment]
@yegor256 paid, thanks, added **30 mins** to your account, payment `000-52b5d2cd`

+30 added to your rating, at the moment it is: [+8463](http://www.netbout.com/b/35008?open=rating)
