### ISSUE TITLE
Launcher.main: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pinaf** [Nerodesk/nerodesk#9]
**$ java -jar target/nerodesk-jar-with-dependencies.jar**

> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
>     at com.nerodesk.Launch.main(Launch.java:65)

Program should either start with a fixed default port or, if you want to enforce the specification of a port, the program should exit cleanly with an error message instead of throwing an Exception.

**Comment by ggajos** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@ggajos got it, tag `bug` is here

**Comment by karato** [comment]
I will ask someone to take care of this task soon

**Comment by karato** [comment]
@ggajos this is your task

**Comment by karato** [comment]
@pinaf thanks for tis bug, I topped your account for 15 mins, transaction `AP-6YF425327C064540A`

**Comment by pinaf** [comment]
@ggajos thanks!

**Comment by karato** [comment]
@ggajos Thank you, I have added **30 mins** to your account in payment/transaction "`AP-5HB31026DE8562846`"; +30 added to your rating, current score is: [+1848](http://www.netbout.com/b/35094?open=rating)
