### ISSUE TITLE
MkDocs tests are missing

### ISSUE THREAD

**Issue by longtimeago** [Nerodesk/nerodesk#90]
We need to cover `MkDocs.names()` and  `MkDocs.doc()` with unit tests.

**Comment by karato** [comment]
we will find someone to do this task, soon

**Comment by karato** [comment]
@alevohin do this task

**Comment by karato** [comment]
@longtimeago many thanks for the bug report, I added 15 mins to your acc, transaction `53752855`

**Comment by alevohin** [comment]
@karato please see PR #121

**Comment by alevohin** [comment]
@longtimeago PR #121 was merged. Please check and close issue.

**Comment by longtimeago** [comment]
@alevohin Thanks!

**Comment by karato** [comment]
@alevohin thanks, paid, **30 mins** to your account, payment ID is `54118552`. +30 added to your rating, current score is: [+1890](http://www.netbout.com/b/35105?open=rating)
