### ISSUE TITLE
MkDoc tests are missing

### ISSUE THREAD

**Issue by longtimeago** [Nerodesk/nerodesk#91]
We need unit tests for all `MkDoc` operations

**Comment by karato** [comment]
I will find a developer for the task soon...

**Comment by karato** [comment]
@krzyk do this task

**Comment by karato** [comment]
@longtimeago thanks for reporting! I topped your account for 15 mins, transaction 53750859

**Comment by krzyk** [comment]
PR #116

**Comment by krzyk** [comment]
@longtimeago changes have been merged to master, please close this issue

**Comment by longtimeago** [comment]
@krzyk thanks!

**Comment by karato** [comment]
@krzyk thanks, I just added **30 mins** to your account, payment `54192933`, 143 hours and 16 mins spent... +30 added to your rating, at the moment it is: [+5239](http://www.netbout.com/b/35035?open=rating)
