### ISSUE TITLE
pom.xml:373-375: Branch coverage is intentionally lowered...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#96]
Puzzle `63-f209efe0` in `pom.xml:373-375` has to be resolved: Branch coverage is intentionally lowered here, in order to get version 0.2 out of the door. Let's raise it back to 50.... The puzzle was created by Yegor Bugayenko on 16-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@krzyk do this task

**Comment by krzyk** [comment]
PR #119

**Comment by karato** [comment]
Closing, thanks all

**Comment by karato** [comment]
@krzyk **30 mins** was added to your account, many thanks for your contribution! The task took 54141335.. +30 to your rating, your total score is [+5224](http://www.netbout.com/b/35035?open=rating)
