### ISSUE TITLE
pom.xml:379-381: Line coverage is intentionally lowered...

### ISSUE THREAD

**Issue by karato** [Nerodesk/nerodesk#97]
Puzzle `63-5fc80ca1` in `pom.xml:379-381` has to be resolved: Line coverage is intentionally lowered here, in order to get version 0.2 out of the door. Let's raise it back to 75.... The puzzle was created by Yegor Bugayenko on 16-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@caarlos0 do this task

**Comment by caarlos0** [comment]
@karato PR is opened #117

**Comment by karato** [comment]
@caarlos0 7 days already, in 48 hours I will re-assign. do not forget to remove the TODO puzzle from the source code. -30 to your rating, your total score is [+1336](http://www.netbout.com/b/35095?open=rating)

**Comment by caarlos0** [comment]
@karato PR is opened.

**Comment by caarlos0** [comment]
@karato we are waiting for #159 here.

**Comment by karato** [comment]
> @karato we are waiting for #159 here.

@caarlos0 sure, we'll wait for #159

**Comment by karato** [comment]
impediment in issue #159 is closed, we can probably try to continue here

**Comment by caarlos0** [comment]
@karato waiting for merge confirmation.

**Comment by caarlos0** [comment]
@karato done.

**Comment by karato** [comment]
2 puzzles were created here: `97-5fc80ca1`, `97-a27c5d4c`

**Comment by caarlos0** [comment]
@karato right.

**Comment by karato** [comment]
I am closing it, thanks all

**Comment by karato** [comment]
@caarlos0 Thanks for your contribution, **38 mins** was added to your account, payment ID is `AP-6ND43509FG663582Y`, 56 hours and 1 min spent total; there is a bonus for fast delivery (age=2889); +38 to your rating, your total score is [+1399](http://www.netbout.com/b/35095?open=rating)

**Comment by karato** [comment]
@yegor256 last 2 puzzles `97-5fc80ca1`/#170, `97-a27c5d4c`/#168 that originated from here were solved
